### ISSUE TITLE
A right-click immediatly followed by a left-click will cause "canvas-drag" event to stick

### ISSUE THREAD

**Issue by rleonard04** [openseadragon/openseadragon#626] opened 2015-03-20 17:06 UTC
Hi, I've come acorss an issue where by a right-click immediatly follows a left-click (or vise versa) the canvas will remain in the "canvas-drag" event until the clicks are repeated - at this point the "canvas-drag" event appears to be disabled and I can no longer navigate the canvas.

**Comment by iangilman** [comment] 2015-03-20 17:53
Paging @msalsbery :)

**Comment by rleonard04** [comment] 2015-03-23 16:34
I've done some furhter debuging around this issue and have found that openseadragon appears to mistake the second click for an additional contact point. I hope this helps. Many thanks.

**Comment by msalsbery** [comment] 2015-03-24 16:36
@rleonard04  What type of pointing device and on which platforms?

**Comment by rleonard04** [comment] 2015-03-25 09:46
@msalsbery, This occurred with a mouse on IE10, and FF.

**Comment by LarissaSmith** [comment] 2017-06-05 22:10
+1. I reproduced this with a mouse in Chrome on Mac and Windows. I noticed issues with the canvas ignoring mouse drags and with the image being stuck to the cursor after the mouse buttons were released. Has any progress been made on this issue?

**Comment by iangilman** [comment] 2017-06-09 18:38
No, no progress. @LarissaSmith would you be up for pursuing a patch?

**Comment by LarissaSmith** [comment] 2017-06-14 21:46
Yeah, I'm planning on looking into this more because our users seem to run into it quite a bit. I'll have to spend some time understanding how the mouse tracking works.

**Comment by iangilman** [comment] 2017-06-16 17:40
@LarissaSmith Great... feel free to ask questions!

**Comment by LarissaSmith** [comment] 2017-06-16 20:25
I concluded that this is happening because browsers limit firing mouse events when two buttons are down at the same time. That's problematic for openseadragon if it captures the pointer-down event, but loses the pointer-up event because a non-primary button is being held down. The mousetracker increments the number of contact points and uses that number to know if the mouse is held down. If the operation is repeated, the contact count gets incremented to 2, so the dragHandler is never invoked. It seems like a mouse should never have more than 1 contact point, and since right-click isn't counted as a contact point, we can detect whether the left button was pressed first when the right button is released. https://github.com/openseadragon/openseadragon/pull/1223

**Comment by iangilman** [comment] 2017-06-22 20:51
Fixed by #1223

**Closed by iangilman** 2017-06-22 20:51 UTC
Labels: bug
