### ISSUE TITLE
ROTATION OF POINTS

### ISSUE THREAD

**Issue by selko** [openseadragon/openseadragon#852] opened 2016-02-17 12:49 UTC
Hello, i was looking in older issues because i´m upgrading Openseadragon.  I upgraded anyways the part of the WSI, navigator and overlays rotation. All works fine, but i have overlays that are simple points on the viewer and don´t rotate. Squares, ellipsis works fine. I ask if i should works for points because reading older issues i found that there is that problem.

Let me know for trying to solve it.

Kind regards

**Comment by iangilman** [comment] 2016-02-17 18:32
@avandecreme you know this area better than I...any thoughts?

**Comment by avandecreme** [comment] 2016-02-17 18:48
> I upgraded anyways the part of the WSI, navigator and overlays rotation.

What is WSI?

Could you make a small example reproducing the bug?
Is it related to #729 and #791 ?

**Comment by boskar** [comment] 2016-02-17 20:46
WSI may stand for Whole Slide Imaging (in microscopy). 

See this example:

http://www.lekarski.katowice.pl/preparat.php?szkielko_guid=EA8AB491C67B479280E6C20E421619D0

vs

http://www.lekarski.katowice.pl/rotate.php?szkielko_guid=EA8AB491C67B479280E6C20E421619D0


I don't use rotation (yet) but I'd expect to have everything rotated. 

Current result is: point annotations move as there is no rotation at all (at 90 deg they move vertically when slide panned horizontally)

non-point annotations follow their location, they are properly anchored, although the shape is not rotated. (more or less like this?)

**Comment by avandecreme** [comment] 2016-02-17 20:55
Thanks for the clarification and the example.
@selko Is that the bug you were experiencing?

Hopefully, this shouldn't be too hard to fix with the latest work on rotation.
Is either one of you willing to look at it?

**Comment by boskar** [comment] 2016-02-17 21:10
@avandecreme I really doubt I can deal with the issue, my skills seem insufficient here : (

On the other hand - https://github.com/openseadragon/openseadragon/issues/791 was opened to make clear whether it will be expected behavior. In my case it's pretty obvious that It should, but I can imagine that other may expect to stay where they put them no matter the rotation is.

**Comment by selko** [comment] 2016-02-17 21:45
Like @boskar example, i have these dots and rectangles or circular areas. With areas works really fine. But the dots remains still when i rotate

**Comment by selko** [comment] 2016-02-17 21:57
I make the rotate implementation reading these issues starting from #88 , #185 . I have the rotateLeft and rotateRight functions implemented and working, but with that issue that i mentioned. I'm really interested in collaborate in Opensedragon but firstly, i need upgrade many things like these to be with yours and working fine with same versions. Kind regards!

**Comment by selko** [comment] 2016-02-17 22:00
@avandecreme , it's exactly the same bug as @boskar have. Kind regards!

**Comment by iangilman** [comment] 2016-03-09 17:47
@avandecreme Is this still an issue on master? @dwrogers seems to think it may not be.

**Comment by avandecreme** [comment] 2016-03-09 18:32
I don't know actually but it looks like it is indeed working on @dwrogers codepen.
Great :)

**Comment by iangilman** [comment] 2016-03-10 18:07
Okay, closing this. Please reopen if it pops up again!

**Closed by iangilman** 2016-03-10 18:07 UTC
Labels: bug

**Comment by boskar** [comment] 2016-04-10 06:49
Just to confirm here: it now works properly 
http://www.lekarski.katowice.pl/notworking/rotate.php?szkielko_guid=40D0E84BCE094A619BFBC3066BCBABAE
http://www.lekarski.katowice.pl/notworking/rotate90.php?szkielko_guid=40D0E84BCE094A619BFBC3066BCBABAE

**Comment by avandecreme** [comment] 2016-04-10 13:21
Thanks for testing! NO_ROTATE should be what you are looking for. I will update the overlays examples on the web site to show the differents modes.

**Comment by selko** [comment] 2016-04-10 17:40
Now it's working there. Great! I have to take a look into the code. Actually, im with the same problem with rotation of points.

**Comment by selko** [comment] 2016-04-10 17:41
With areas works fine for me.

**Comment by selko** [comment] 2016-04-10 17:42
There is some place where i can find new modifications? Kind regards!

**Comment by avandecreme** [comment] 2016-04-10 17:48
This is the related PR: https://github.com/openseadragon/openseadragon/pull/896/files

To setup a non-rotating overlay you need to do:
```javascript
    var overlay = {
        id: 'right-arrow-overlay',
        x: 0.2008,
        y: 0.4778,
        placement: 'RIGHT',
        rotationMode: OpenSeadragon.OverlayRotationMode.NO_ROTATION
    };
```
