### ISSUE TITLE
White lines appear while zooming the image to deep levels on FF (like squares for the tiles) on version 2.4.0

### ISSUE THREAD

**Issue by AsmaAq** [openseadragon/openseadragon#1683] opened 2019-07-23 06:05 UTC
After I've upgraded the openseadragon to 2.4.0 I can see white lines when zooming to deep levels

![image](https://user-images.githubusercontent.com/14885860/61686685-04f5e900-ad29-11e9-9137-8b57475a54ec.png)

How can I remove these lines? 

Thanks

**Comment by iangilman** [comment] 2019-07-23 20:31
I don't think this happens in all cases, so it would be good to narrow down the specifics of your case. What kind of tiles are you using? What are your settings? 

My guess is that it's related to https://github.com/openseadragon/openseadragon/pull/1470. You might try building a new OpenSeadragon with that change reverted to see if it fixes the issue. If it does, we'll have to figure out how to use the right strategy for the right circumstances (since that patch fixed other kinds of seams).

**Comment by AsmaAq** [comment] 2019-07-24 08:24
It happens on FireFox only.

What do you mean by "You might try building a new OpenSeadragon with that change reverted to see if it fixes the issue" ?

**Comment by AsmaAq** [comment] 2019-07-24 08:57
I turned the debug mode to true so we can see the tiles, looks like the white lines are the same as debug lines?
Debug mode "true"
![image](https://user-images.githubusercontent.com/14885860/61779717-def44580-ae09-11e9-9330-29c03d22529a.png)


Debug mode "false"

![image](https://user-images.githubusercontent.com/14885860/61779909-30043980-ae0a-11e9-83b0-7fde722ace06.png)

**Comment by MisterX2000** [comment] 2019-07-24 13:35
I've noticed that this problem occurs when you select `png` as a file type in [vips](https://github.com/libvips/libvips).

**Comment by iangilman** [comment] 2019-07-24 18:46
Turns out we've already discussed this issue in https://github.com/openseadragon/openseadragon/issues/1591. No one followed up though. Someone still needs to get to the bottom of how to cover all cases. One option, I suppose, would be to add another flag. Still, it would be nice if we could understand the difference between the #1470 case and the one covered here (and in #1591). I think it may have to do with the image in #1470 being mostly semi-transparent, whereas in #1591 and this issue the image is mostly opaque.

Either way, @MisterX2000 is correct: It only happens for PNG tiles. @AsmaAq I assume you need your tiles to be PNG, not JPEG?

@AsmaAq What I meant by "You might try building a new OpenSeadragon with that change reverted to see if it fixes the issue" is you could pull down this repository and build OpenSeadragon yourself. You could then go into your copy of the OSD code and change the code that was changed in #1470 back to how it had been prior to that PR (it's a very small change). You could then rebuild and try it. That would also be the first step to figuring out how to make a fix to OSD that supports both scenarios.

**Comment by MisterX2000** [comment] 2019-07-24 21:29
I'm currently trying out webp (lossless) and it works just fine and doesn't have these outlines around the tiles on Firefox.
I hard coded it into the [list of file formats](https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js#L2511) for testing.
And here's an example: https://misterx.3server.de/WebMap/OpenTTD-Altis/

**Comment by raphaelfv** [comment] 2019-07-25 16:38
I had generated the tiles using [openzoom.deepzoom](https://github.com/openzoom/deepzoom.py) for Python 2 with 'png' format and I can confirm the tiles are shown in Firefox with the grid lines. Based on  MisterX2000's comment, I had changed the "tile_format" input from the ImageCreator's constructor from "png" to "jpg" and I can also confirm the lines are gone. Besides, using 2.3.1 version, the lines aren't shown no matter if one uses the generated tiles in 'png' or 'jpg'.

**Comment by iangilman** [comment] 2019-07-25 18:02
The reason this issue only shows up with PNG is because PNG can potentially have transparency, so we have to treat it differently. I imagine you would see a similar effect if you set the opacity of your TiledImage to something other than 1.

Regarding WebP, evidently that format supports transparency as well, but since OSD doesn't know about it, it doesn't treat it as a transparent image. Also, as discussed in https://github.com/openseadragon/openseadragon/issues/1622, keep in mind that WebP doesn't work in every browser (most notably, Safari, which is the only browser option for iOS devices).

**Comment by AsmaAq** [comment] 2019-07-29 06:31
@raphaelfv yes I didn't face this issue before on 2.3.1

@iangilman I need the tiles as PNG, I've pulled the repository and reverted the change mentioned in tile.js, but how can I rebuild "openseadragon.min.js" after my change ? so I can include it in my code. 

![image](https://user-images.githubusercontent.com/14885860/62026387-8cd56a80-b1e3-11e9-9e69-07b1fac540d4.png)

**Comment by alvaromartmart** [comment] 2019-07-29 08:07
@AsmaAq to build it, execute:
`npm run prepare`

if everything goes well, the updated `openseadragon.min.js` will be inside the `build/openseadragon` folder

**Comment by AsmaAq** [comment] 2019-07-29 09:05
@alvaromartmart can u please tell me in which directory/path to execute the npm ? 
the file I changed is under openseadragon\tags\v2.4.1\src

**Comment by alvaromartmart** [comment] 2019-07-29 10:20
@AsmaAq you should execute it from the root directory where the package.json file is. Most likely the 'openseadragon' folder, if you cloned the repository directly.

**Comment by AsmaAq** [comment] 2019-07-29 11:42
@alvaromartmart Thank you!

I got this :

![image](https://user-images.githubusercontent.com/14885860/62045818-00d93800-b20f-11e9-9563-0993b90c2062.png)

any thoughts?

**Comment by AsmaAq** [comment] 2019-07-29 11:55
@alvaromartmart Thank you!

It worked fine when I reverted the code in tile.js file. So now no white lines on the image on FF! 

how can we get this change? will it be verified and added to the src?

Thanks

**Comment by iangilman** [comment] 2019-07-29 18:14
[Tagging some additional interested parties: @Dvidan, @Kampii]

@AsmaAq The problem with just reverting that change is that it will break the scenario that that code was meant to fix. We need to come up with a new solution that solves both that scenario and your scenario.

As mentioned above, that new fix could be yet another option given to the viewer at creation, but ideally we'd be able to find some middle ground that worked in both scenarios (or detected which scenario was applicable) so we don't have to complicate the API further. 

Is anyone on this thread up for pursuing this?

**Comment by AsmaAq** [comment] 2019-08-19 09:23
@iangilman Thanks for your help.

Any updates on this so we can now if it has a solution soon? or we need a workaround or smth 

Thanks

**Comment by iangilman** [comment] 2019-08-19 17:40
@AsmaAq It doesn't look like anyone has volunteered to take this issue on. OpenSeadragon is volunteer driven (or sometimes people are hired to work on features.). Would you like to dive into figuring out how to make the real fix?

If not, meanwhile you can use the custom build of OpenSeadragon you made while testing the reverted code.

**Comment by AsmaAq** [comment] 2019-08-21 09:59
@iangilman I would like to dive into the code and solve a real fix but unfortunately now I don't have time, soon I will if no one handled the case. 

So in the meanwhile I'll use the custom build. It will affect anything else? what are the impacts of it?

**Comment by iangilman** [comment] 2019-08-21 17:32
@AsmaAq Sounds good! Let me know as you have questions :)

There should be no downside to your using the custom build in the meantime, assuming your images aren't the sort that would show seams under the circumstances that https://github.com/openseadragon/openseadragon/pull/1470 resolved.

Basically, we have two potential types of transparent images... Those that are mostly opaque, like the ones you're using, and those that have large semitransparent areas (as in https://github.com/openseadragon/openseadragon/pull/1470). The trick is to see if we can find a setting that works in both cases (or if not, provide a switch so that you can select which case is yours). By making that custom build you're basically hard wiring that switch, saying you only have the mostly opaque type of image.

**Comment by AsmaAq** [comment] 2019-08-27 13:00
@iangilman  Okay Great. Thank you :)

Can you give me an image where i can see the issue in #1470 ? will start investigating the code,

**Comment by AsmaAq** [comment] 2019-09-02 13:51
@iangilman I've tried the code with overlap =1 with the code below and transparent image and i couldn't see any lines.

context.clearRect(
                position.x + 1,
                position.y + 1,
                size.x - 2,
                size.y - 2
            );
So did you see the lines in that case before?

looking at these all cases together I think the solution in which the value of "overlap" is countered is reasonable here like below:

 context.clearRect(
                position.x + overlap,
                position.y + overlap,
                size.x - (2*overlap),
                size.y - (2*overlap)
            };

so in my case where the overlap is 1, it will work , and in this case when the overlap is zero it will work as well. 

What do you think?

**Comment by iangilman** [comment] 2019-09-04 20:33
Hmm... I'm definitely getting dark lines with overlap of 1, using a test image like I recommended. Here's my test image:

[semitransparent.zip](https://github.com/openseadragon/openseadragon/files/3576345/semitransparent.zip)

...And here's what it looks like in Firefox with an overlap of 1: 

<img width="526" alt="image" src="https://user-images.githubusercontent.com/338989/64288738-a7ec7600-cf17-11e9-85ba-8529d6632fc1.png">

If I change it to an overlap of 0, then I get the light lines:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/338989/64288836-ea15b780-cf17-11e9-9f41-1ab774cd9f7d.png">

The dark lines are because there's too much overlap, and the light lines because there's not enough. I've played with a few overlaps in between, though, and nothing is perfect. I think it comes down to the fact that pixels are still pixels, even if you give fractional values. So maybe what we need to do is round to the nearest whole pixel in this case. I tried this:

```
//if we are supposed to be rendering fully opaque rectangle,
        //ie its done fading or fading is turned off, and if we are drawing
        //an image with an alpha channel, then the only way
        //to avoid seeing the tile underneath is to clear the rectangle
        if (context.globalAlpha === 1 && this._hasTransparencyChannel()) {
            // Round to the nearest whole pixel so we don't get seams from overlap
            position.x = Math.round(position.x);
            position.y = Math.round(position.y);
            size.x = Math.round(size.x);
            size.y = Math.round(size.y);

            context.clearRect(
                position.x,
                position.y,
                size.x,
                size.y
            );
        }
```

...And the results seem good. What do you think?

**Comment by AsmaAq** [comment] 2019-09-05 07:59
I applied your change and no lines were shown, but I can see alot of flickering when zooming to deep levels as shown in the video. 


[flickering.zip](https://github.com/openseadragon/openseadragon/files/3578122/flickering.zip)

Maybe it happened because of the rounding so some areas are matched?

**Comment by iangilman** [comment] 2019-09-05 21:02
What do you mean by flickering? I'm not seeing anything unusual in the video you sent (except there are some trails, but I assume that's just the video itself). Have you tried with and without and can you tell a difference? I've tried on my computer using the Duomo image (the one from the OSD front page), and I can't tell the difference in the animation with and without the patch. This is on Mac Firefox and Mac Chrome. That image is 13000 pixels wide... How big is the one you're testing with?

I believe the tile positions we're talking about here are in web coordinates (or possibly even Canvas coordinates), so they shouldn't behave any differently zoomed in vs zoomed out.

**Comment by AsmaAq** [comment] 2019-09-09 18:09
like the image is vibrating in its place then become stable. 

I've recorded a video before and after the change (before is also includes the revert of the code in #1470 I think it is related too).

[beforeAndAfterChange.zip](https://github.com/openseadragon/openseadragon/files/3591957/beforeAndAfterChange.zip)

The image is 3600*2700 (width,height)

**Comment by iangilman** [comment] 2019-09-09 18:31
Ok, I see what you're talking about. Having the before/after is helpful.

I'm not sure if there's anything that can be done about it. We may have to choose between seams and vibration. I suppose we could limit the fix just to Firefox, since that's where the seams are showing up.

Keep in mind that the only reason you're not seeing seams when you revert #1470 is because your tiles don't actually have any transparency. Can you remind me again why you need to use PNG tiles even though you're not using transparency?

**Comment by AsmaAq** [comment] 2019-09-09 18:36
We keep it to the user to choose how he wants the images to be generated, so we have PNG as an option.

What about the overlap? we generate tiles with overlap=1 always, what if we used 0? does it affects the smoothing when moving and zooming the image? 

I'm asking about it because if we user overlap=0 we may not have any issue here right?

**Comment by iangilman** [comment] 2019-09-10 20:29
Good question! I tried making a test file with 0 overlap, and the results were the same. You can play with it if you want: 

[semitransparent-overlap0.zip](https://github.com/openseadragon/openseadragon/files/3597573/semitransparent-overlap0.zip)

And yeah, if you're giving your users the option to use PNG, then you really don't have any control over whether they are using PNG with transparency, so just reverting #1470 isn't really going to work (since that only works if the PNG doesn't have transparency).

The fact that it's not an issue on Chrome implies that the two browsers are handling fractional pixels in canvas differently somehow. I'm not sure if there's any thing to be learned by digging into that angle.

I'm certainly open to other ideas, but so far it seems that forcing to pixel boundaries for PNGs on Firefox is the best option we have.

**Comment by AsmaAq** [comment] 2019-09-11 05:23
Yes seems Firefox has different margin of rounding pixels at some point. 

But Unfortunately forcing pixels boundaries on FF  solution is not applicable on our system because the vibrating in deep zooms is so obvious when pixels are rounded. 

I don't know more in this area of code to change :( I hope we can find other ideas to apply here.

**Comment by iangilman** [comment] 2019-09-11 18:04
Fair enough. I'll let you know if I think of anything else, but at the moment I'm stumped.

I suppose there might be a way to file an issue on Firefox... You'd have to come up with a simplified repro... Drawing two semitransparent rectangles next to eachother where they touch at a fractional pixel. That might even be a good way to get some more perspective on the problem.

**Comment by iangilman** [comment] 2019-09-26 16:51
I've gone ahead and made a pull request with the rounding "fix" just in case it's useful to anyone investigating this: https://github.com/openseadragon/openseadragon/pull/1713 It has the chunkier animation, so I don't expect it's the final fix, but I figure it might be a step.

Anyway, I think maybe the next step for anyone who wants to pursue this further is to make a non-OpenSeadragon test bed where you draw two semitransparent rectangles next to each other where they touch at a fractional pixel and see if there's any way to get that to work on Firefox.

**Comment by iangilman** [comment] 2019-10-21 18:49
Random thought… All of this has to do with the fact that we assume PNG tiles have transparency in them, with the assumption you would use JPEG if you didn't need the transparency that PNG provides. That said, presumably there are other reasons people would use PNG, for instance because it's a lossless format. One option might be to provide a flag that allows the developer to say "yes, these are PNG tiles, but there is no transparency, so you don't need to worry about overlap being a problem". I suppose we could even autodetect the transparency or lack thereof on a tile by tile basis (since we're already copying the image data into canvases).

**Comment by karin-toth** [comment] 2019-10-30 14:46
Hi, I have done some testing and reading on blend modes and compositing in canvases. When painting the tiles we should probably use composite operation 'lighter'. This helps with the sub-pixel problems since this operation adds the alpha values (also blends the colors). When we have a seam with overlap 0 and tile sizes consisting of half a pixel (due to zooming or scaling), the left tile and right tile both paint on the same column of pixels, but contribute with half a pixel each. Alpha-composing with addition is the best option here since that would add up correctly in that seam. Try adding `context.globalCompositeOperation = 'lighter';` to line https://github.com/openseadragon/openseadragon/blob/3bbfbcbc0e136405e3f8ed95316d36255dba835f/src/tile.js#L339 A note; I commented out the line https://github.com/openseadragon/openseadragon/blob/3bbfbcbc0e136405e3f8ed95316d36255dba835f/src/tiledimage.js#L1624 to get correct tile size with overlap 0 as discussed in #1722.  This should technically remove all visible seams but unfortunately not all the time. After some testing with transparent/opaque tiles and different sizes I have come to the conclusion that everything seems to be rendered correctly except that firefox has a bug regarding transparency and sub-pixel rendering. If the tile size is something .8 then the left tile has alpha 204 (255*0.8) and the right one alpha 51 (255*0.2) in the seam, both adding up to 255. Firefox lets the left tile contribute with 204 but the right one with only 10, adding up to 214 and thus showing a seam. To me this seems incorrect. IE and edge seem to have the same problems. Chrome who doesn't seem to do sub pixel rendering, has no such problems. 
Please let me know if you don't follow my reasoning here. It's not that easy to convey graphics problems through text.  
Rounding sizes causes wobbly zooming effects as you noted. Even if we round the positions and sizes we probably get problems with fixed-point precision showing up as seams in some cases. Painting the seams manually is an option but that is quite an undertaking. Removing the line mentioned in #1722 and using composite mode 'lighter' for tile painting is an improvement at least.

**Comment by iangilman** [comment] 2019-10-30 20:48
Oh! Transfer modes is an interesting angle! It does seem to improve things, though as you said it's not perfect. Here's what I'm seeing with [semitransparent.zip](https://github.com/openseadragon/openseadragon/files/3576345/semitransparent.zip) on Firefox: 

![image](https://user-images.githubusercontent.com/338989/67897007-c12a3100-fb1a-11e9-9a7f-8ebc9d4cf974.png)

Good enough that it's worth making the change, I think! Would you be up for making a pull request with it? I think probably it's worth doing that separately from the overlap 0 fix for #1722, just to keep things straight.

> Chrome who doesn't seem to do sub pixel rendering, has no such problems.

What does it do instead of sub pixel rendering? Seems like that would be no different than rounding, but I'm not seeing any wobbly effect in Chrome...

Thank you for your detailed analysis and clear write up!

**Comment by karin-toth** [comment] 2019-10-31 10:51
I'd love to contribute! Yes, two pull-requests is probably best since it's two issues. I think I need access rights to this repository to be able to create branches, I'm getting 403's at the moment when pushing new branches. Or I have missed some authentication on my side. 

Chrome scales the image correctly, so all pixels within the tile are rendered with some kind of sampling method, but the partial pixels on the edges are completely opaque so they are painted straight on top of each other, rather than some kind of blend which is the case for firefox. So both chrome and firefox do the same sampling of the tile when scaling it, but handles transparancy of the edge pixels differently.

**Comment by karin-toth** [comment] 2019-10-31 11:06
@sverbist Interesting! What version are you on? I just tested with 70.0 64-bit and still see seams with dark tiles with transparency (i.e. png). I'm using 2x2 tiles with tile size 256 and 0 overlap. Rendering this in a container of 513 by 513 and zoom level 1.0 shows seams. If you replicate this setup, do you see seams?

**Comment by sverbist** [comment] 2019-10-31 12:23
@karin-toth 
Sorry for the false hope. I missed the part about this only affecting png images. I ran into this problem a while ago and since then we switched to jpg for another reason and we noticed the lines vanished. We erroneously concluded it must've been FF update rather than the filetype switch. My bad :(
With png's the problem is still very much alive.

**Comment by karin-toth** [comment] 2019-10-31 13:14
@sverbist no problem :)

**Comment by iangilman** [comment] 2019-10-31 17:35
@karin-toth great! You'll need to make a fork to make a PR (more info here: https://github.com/openseadragon/openseadragon/wiki/Making-a-Pull-Request).

Thanks for the explanation on Chrome's edge handling. Seems like a smart approach.

**Comment by karin-toth** [comment] 2020-01-11 18:03
Hi! I've been working on a webGL renderer for quite some time now, but as many other things, it's more complex that it seems. I got something to work, but taking it from a seems to work-state to the type of fail-safe production code that is required takes more time than I thought. So I would have loved to contribute, but I just don't have the time to complete this. 
Best regards, Karin Toth

**Comment by iangilman** [comment] 2020-01-13 18:26
@karin-toth I completely understand! Thank you for the update. Might you be able to share your work in progress somewhere in case it's helpful to someone else who might want to pick up the torch?

**Comment by karin-toth** [comment] 2020-01-14 12:59
Of course! The branch can be found here:
https://github.com/karin-toth/openseadragon/tree/kato-webgl
I'm of course open for answering questions and other help in the future if
someone wants to continue.

**Comment by iangilman** [comment] 2020-01-14 22:04
Wonderful, thank you! I've now linked to it from a couple of relevant issues. :-)

**Comment by vudayagirivaibhav** [comment] 2020-04-07 09:18
@iangilman  I face the same issue. My openseadragn version is 2.3.2. the format used is jpg, the tileoverlap is 0.

**Comment by iangilman** [comment] 2020-04-17 21:23
@vudayagirivaibhav Interesting. Can you share a link? Have you tried with tile overlap?

**Comment by elcferreira** [comment] 2021-06-29 17:00
Hello @iangilman, I've read the whole issue, but I didn't found the fix.

Should I use a `branch` to solve the problem on firefox?
I'm generating from JPG, but the problem still happening.

I'm using this verion: 
`"openseadragon": "^2.4.2",`

DEMO:
http://piranesi.staging.mircloud.de/de/zoomtool/2

**Comment by iangilman** [comment] 2021-07-02 18:29
@elcferreira the problem arises when your tiles are PNG, regardless of what the original image was. I can see in your example that you are using PNG tiles. Can you reconvert the image into JPG tiles?

**Comment by iangilman** [comment] 2021-12-23 19:56
While we have been unable to find an automatic fix for this issue, we've now landed a set of options that allow you to fix the issue based on your needs and preferences: #2075. I'm going to close this issue and we can start a fresh one if there are new ideas for how to fix it more robustly and/or automatically.

**Closed by iangilman** 2021-12-23 19:56 UTC
Labels: bug
