### ISSUE TITLE
Bug - Safari iOS blocks all interactions but OpenseaDragon canvas

### ISSUE THREAD

**Issue by lisandro-lifelike** [openseadragon/openseadragon#877] opened 2016-03-11 12:26 UTC
When using the library in Safari iOS 9.2 and after pinch zooming a bit, sometimes happens that the whole browser gets locked for user interactions. Though, the canvas where OpenseaDragon makes the drawing still works and reacts fine.
We first noticed this on a project we are developing, but then also tested it on your demo https://openseadragon.github.io/ and still got the same behaviour error.
Sometimes it happens that the browser comes back to life after a while and everything works again. But sometimes it doesn't, it gets blocked for good until the user refreshes the page.

The easiest way to reproduce seems to be to open it in the iOS simulator and stressing it by pinch zooming a lot. On the actual device (iPhones 5s, 6, 6s) it takes more tries to get the error to happen but it happens as well.

As always this is pretty urgent, so would really appreciate fast response :)
Thanks for an otherwise awesome library!

**Comment by iangilman** [comment] 2016-03-11 18:33
Thank you for the report! OpenSeadragon is purely volunteer, so there's no one dedicated to fixing issues such as this. It's possible @msalsbery might have some ideas for things to pursue (since he did much of the touch interaction code) but he may not have the bandwidth to debug it. If you'd like to dig into the problem, I'm sure people here can pitch in with answers to questions, though. 

I assume you've tested it with Android as well and not found the issue there? When you say the whole browser gets locked, you mean that other controls that are unrelated to OSD don't work either? When you say, the OSD still reacts fine, do you mean that you can still interact with it in this state?

**Comment by lisandro-lifelike** [comment] 2016-03-14 09:21
@iangilman thanks for the answer!
I really hope someone else has encountered such error before because we couldn't nail down what the problem is yet. 
From what we found out so far, it has something to do with pinch zooming the canvas.

Yes we tested it on Android and it works perfectly without issues.
With iOS however, when I say whole browser gets locked what I mean more in details is: Every interaction within the page stops working (such as scroll the page, or click on any <a> won't work), but the browser UI doesn't stop working (such as address bar, refresh buttons, etc), so the only way for us to move on from the error is by refreshing the site.
When I say OSD works fine, yes I mean that even though the page stops reacting to touches, OSD canvas still works just as fine. We can pinch, pan, etc.

**Comment by iangilman** [comment] 2016-03-14 17:16
@lisandro-lifelike Thank you for the additional info. @msalsbery Any thoughts on what might cause this?

**Comment by iangilman** [comment] 2016-03-18 18:28
I wonder if this is issue is related #869. @lisandro-lifelike Could you try setting flickEnabled to false and see if that helps?

**Comment by iangilman** [comment] 2016-03-21 17:50
Perhaps #884 will fix this?

**Comment by dlukez** [comment] 2016-04-29 08:36
I'm on iOS 9.2 as well and can reproduce this issue with the following steps:

1. Place a single finger on the screen
2. Place another finger on the screen
3. Simultaneously remove both fingers at the same time (needs to be timed well)

**Comment by iangilman** [comment] 2016-04-29 16:53
Thank you for the repro tip! Unfortunately I can't reproduce it (tested on iPad, iOS 9.3.1 on the OpenSeadragon home page). Maybe it's been fixed in the more recent OS, or maybe I just can't get the timing right?

**Comment by dlukez** [comment] 2016-05-03 02:22
@iangilman I just repro'd it on my iPhone with iOS 9.3.1. Took me a few times to get the timing right...

**Comment by dlukez** [comment] 2016-05-06 07:28
Out of curiousity, I made the following script to reproduce the issue on http://openseadragon.github.io using Chrome Device Emulation.

    (function () {

      //--------------------------------------------
      // OpenSeadragon #930
      // 
      // Steps to reproduce:
      //   1. In Chrome, go to http://openseadragon.github.io
      //   2. Open Developer Tools and turn on Device Emulation
      //   3. Refresh the page
      //   4. Run this script in the console
      //
      // Aside from OpenSeadragon itself, the rest of the page
      // should not longer respond to swipes, taps, etc.
      //
        
      var canvas = document.querySelector('.openseadragon-canvas');
      var touches = [];
      var log = e => { console.log(e) };
      document.addEventListener('touchstart', log, true);
      document.addEventListener('touchend', log, true);

      touchstartEvent({
        clientX: 235.81300354003906,
        clientY: 1108.625,
        force: 1,
        identifier: 0,
        pageX: 235.81300354003906,
        pageY: 1108.625,
        radiusX: 35.21875,
        radiusY: 35.21875,
        rotationAngle: 0,
        screenX: 2854,
        screenY: 583,
      });

      touchstartEvent({
        clientX: 719.68798828125,
        clientY: 1497.56298828125,
        force: 1,
        identifier: 0,
        pageX: 719.68798828125,
        pageY: 1497.56298828125,
        radiusX: 35.21875,
        radiusY: 35.21875,
        rotationAngle: 0,
        screenX: 3012,
        screenY: 710,
      });

      touchendEvent();

      //--------------------------------------------
      // HELPERS
      //
      function touchstartEvent(opts) {
        var touch = new Touch(Object.assign({}, opts, {
          identifier: touches.length + 1000,
          target: canvas
        }));

        touches.push(touch);

        var event = new TouchEvent('touchstart', {
          view: window,
          bubbles: true,
          cancelable: true,
          touches: touches,
          targetTouches: touches,
          changedTouches: [touch],
        });

        canvas.dispatchEvent(event);
      }

      function touchendEvent() {
        var event = new TouchEvent('touchend', {
          view: window,
          bubbles: true,
          cancelable: true,
          touches: [],
          targetTouches: [],
          changedTouches: touches,
        });

        canvas.dispatchEvent(event);
      }

    })();

**Comment by iangilman** [comment] 2016-05-12 20:51
@dlukez Nice! Can you try it with the latest code from master to see if #884 has fixed it? Are you up for digging in to see if you can find a fix? I'm happy to point you toward the applicable code.

**Comment by iangilman** [comment] 2016-05-12 21:01
@dlukez Sorry, now I see you've already made a PR! Wonderful :)

**Closed** 2016-05-17 17:44 UTC
Labels: bug
