### ISSUE TITLE
Control on resize state  while change the screen with and open the fullscreen

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1178] opened 2017-05-01 06:36 UTC
Hi  thx again for your support

I m using the solution for keep the zoom : http://codepen.io/iangilman/pen/BWKKxQ 

my question is about the resize 

how can I control the resize to support responsive or similar to that, because I have 2 problem 

1- if I open the full screen  the image is looking bad , i guess cause of the autoResize = false ( but if i split the screen to be with 2 images . and then open the full screen its looks good
2- If i open the chrome debugger for second or change the width of the browser I have to refresh the page to fix it . (which it can not be done for example on the full screen mode)

how can I fix or work with the resize situation 

btw . when open the full screen on chrome its looks like it close and then open again very fast, it can be fixed ? 
. 
thanks

**Comment by iangilman** [comment] 2017-05-01 16:38
Yes, you'll need to handle resizing yourself. This should do it:

```
$(window).on('resize', maintainZoom);
```

I'm not sure if there's anything that can be done about the little flicker on full screen on Chrome. I don't think it's actually closing and opening again, though.

**Comment by johnico** [comment] 2017-05-03 08:34
@iangilman  thanks , i will try to play with 
do you know how to get rid of unnecessary animations when open the 2 images , and now  the image came from top and "jump" .  I m trying to figure it out but did not mange 
what i m trying to achieve is just to show the image maybe only with fadein 

thx

**Comment by iangilman** [comment] 2017-05-03 17:31
You're saying it triggers for both going into fullscreen and leaving fullscreen? It's true, that's what that event does. You can take a look at the event object it passes you and look at its `fullscreen` property to know if you're entering or exiting.

**Comment by johnico** [comment] 2017-05-04 10:37
Yes but how can I fix  the issue with the resize in the full screen .
Cause I get the console.log when I open the full screen 

Thx :)

**Comment by iangilman** [comment] 2017-05-04 17:00
I'm sorry, I can't reproduce the full screen issue with http://codepen.io/iangilman/pen/BWKKxQ ...I go into full screen and then come back out with both one image or two, and they always look fine when I get back. I tested in Mac Firefox and Chrome. Seems like everything works?

**Comment by johnico** [comment] 2017-05-06 09:29
yes my mistake , its working! thx a lot

**Comment by johnico** [comment] 2017-05-08 14:59
Hi its not working when you on full screen on the browser and then click on full screen button and you will see the error - very strange :)  did not manage to fix it

**Comment by iangilman** [comment] 2017-05-08 17:37
It may be a legitimate timing issue. Try a setTimeout of 1 rather than 200 and see if it still works. If so, it's just a matter of exiting the current call frame, and is a fine solution.

**Closed** 2017-12-28 01:17 UTC
Labels: question
