### ISSUE TITLE
wrapHorizontal: Continuous scrolling moves panorama out of viewer area

### ISSUE THREAD

**Issue by alex197** [openseadragon/openseadragon#555] opened 2015-01-06 10:31 UTC
I noticed that if I take a 360° panorama with wrapHorizontal=true and I keep scrolling right (left), eventually not enough tiles will be loaded and black background will appear on the right (left) side of the viewer area:
![continuous](https://cloud.githubusercontent.com/assets/10416237/5627305/b08d841c-9596-11e4-957b-6c2f7617226c.png)
This happens both with Chromium 37 and Firefox 34 (both under Ubuntu), so I assume it is not browser specific. It does however seem to be source specific, I was not able to reproduce it with the examples provided at https://openseadragon.github.io/examples/tilesource-tms/ and https://openseadragon.github.io/examples/tilesource-custom/ .
If you want to try and reproduce the issue,  you can use https://openseadragon.github.io/examples/tilesource-osm/ or a 360° panorama from my website (running the latest openSeadragon v1.2.0): http://alexbartl.de/alex/panorama.html .

**Comment by iangilman** [comment] 2015-01-06 17:54
And if you keep scrolling you just end up with emptiness? Interesting. Does anything show up in the console? 

I tried on your site, but it looks like wrapHorizontal is not on for those panoramas. Even so, it seems sometimes we're not clipping properly, and the edge-most tile that should appear does not. 

I'm curious if it's any different in the code from the multi-image branch: #446.

**Comment by alex197** [comment] 2015-01-06 18:10
Yes, I can scroll into complete emptiness. The console stays completely empty.
wrapHorizontal is only on for certain panoramas, namely those marked with a "(360°)" in the caption, e.g. the Toronto one, 4th from top.

By the way, thanks for a great tool!

**Comment by iangilman** [comment] 2015-01-07 17:36
Thanks! Great to see it powering such lovely photos. Sorry it's not working perfectly.

Okay, yes, I can reproduce. It looks like what's happening is that every time you wrap, a little bit of error creeps into the drawer's clipping region. Once you've wrapped enough times, the error has built up enough that it fills the entire viewer. This error seems to be much more dramatic for super-wide images like you have; square images can wrap many times without encountering it. 

For anyone who wants to debug this, here's a code snippet you can add to /test/demo/basic.html:

```
        var viewer = OpenSeadragon({
            id: "contentDiv",
            wrapHorizontal: true,
            prefixUrl: "../../build/openseadragon/images/",
            tileSources: {
                Image: {
                    xmlns:    "http://schemas.microsoft.com/deepzoom/2008",
                    Url:      "http://alexbartl.de/alex/galerie/panoramen/dzi/torontocn_files/",
                    Format:   "png",
                    Overlap:  "4",
                    TileSize: "256",
                    Size: {
                        Height: "2594",
                        Width:  "20632"
                    }
                }
            }
        });
```

The problem is probably in drawer.js; searching for wrapHorizontal might be a good first step. 

I've tried with wrapVertical, and that can get a similar effect vertically as well.

**Comment by avandecreme** [comment] 2016-04-21 23:54
I spotted the reason for that issue.

TiledImage is calling `TileSource.getTileAtPoint` with point.x possibly below 0 or above 1 (and point.y above aspect ratio) here https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L946-L947
However `TileSource.getTileAtPoint` does not account for the fact that the last tile of a row (or column) can be smaller than the others.

An quick fix would be to make that method account for that but I think tile source implementers shouldn't have to worry about that. Besides, [ImageTilesource currently always return (0,0)](https://github.com/openseadragon/openseadragon/blob/master/src/imagetilesource.js#L175) so it doesn't support wrapping at all.

On the other hand, modifying TiledImage to correctly handle wrapping is a bit more tricky.

I am still in favor of that second option though.

**Comment by iangilman** [comment] 2016-04-22 17:55
Awesome, great discovery! I agree that it should be TiledImage's responsibility; TileSources shouldn't have to think about wrapping.

**Comment by iangilman** [comment] 2016-06-21 17:53
@voidvolker has expressed interest in working on this, but may need some additional info from @avandecreme.

**Comment by VoidVolker** [comment] 2016-07-28 22:47
`TileSource.getTileAtPoint` is used only in one place in OSD and I think this is correct place for fix. 
Also:
1) Viewport can have any coords;
2) `getTileAtPoint` return tile from point in viewport coordinates.
=> `getTileAtPoint` must support any coordinates, not only 0:0-1:1.

**Comment by VoidVolker** [comment] 2016-07-29 15:13
Meet small bug: when page loads, OSD load allmost all tiles, but left and right column are empty and loads later, above 1-2 seconds.

**Comment by iangilman** [comment] 2016-07-29 20:22
This has been fixed by #987!

**Closed by iangilman** 2016-07-29 20:22 UTC
Labels: bug

**Comment by alex197** [comment] 2016-07-30 11:41
Thank you! It is now working smoothly.

BTW, the URL for the site changed, it is now http://alexbartl.de/panorama.html . Feel free to also update the in-the-wild link.

**Comment by iangilman** [comment] 2016-08-01 16:59
@alex197 Thanks for the heads up! Fixed: http://openseadragon.github.io/examples/in-the-wild/
