### ISSUE TITLE
IIIF scaling problem in 4.1.0 that is not present in 4.0.0

### ISSUE THREAD

**Issue by craigberry** [openseadragon/openseadragon#2427] opened 2023-10-11 11:54 UTC
The following boiled-down reproducer displays a badly distorted image with OpenSeadragon 4.1.0, but works fine with 4.0.0. Basically the aspect ratio appears to get lost and the image gets squashed vertically, although I've also seen cases where it gets squashed horizontally.  It's easy to reproduce but I'm afraid I don't know how to debug it.  Any help appreciated.

```html
<html>
<head>
    <title>OpenSeadragon 4.1.0 Problem with Ransom Center IIIF Images</title>
    <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/openseadragon/4.1.0/openseadragon.js'></script>
    <style type="text/css">.openseadragon1 { width: 500px; height: 800px; }</style>
</head>
<body>
    <div><p>Ransom Center IIIF problem</p><p>Change 4.1.0 to 4.0.0 for distortion to go away</p></div>
    <div id="facsimile" class="openseadragon1"></div>
    <script type="text/javascript">
        var facsimileUrl = 'https://hrc.contentdm.oclc.org/digital/iiif/p15878coll17/8057';
        var viewer = OpenSeadragon({
                id: "facsimile",
                prefixUrl: "https://cdnjs.cloudflare.com/ajax/libs/openseadragon/4.1.0/images/",
                crossOriginPolicy: "Anonymous",
                tileSources: [facsimileUrl + '/info.json']
        });
    </script>
</body>
</html>
```

**Comment by craigberry** [comment] 2023-10-13 02:39
I've done a manual bisect that shows the problem was introduced by 0c358c140dae8bcd5cbc568ef6236a840af84efe.

**Comment by pearcetm** [comment] 2023-10-13 14:35
Thanks for digging into it and finding that info, @craigberry. @ruven it looks like this was caused by a PR you made to fix another issue; would you be able to take a look at this as well?

**Comment by ruven** [comment] 2023-10-17 11:38
I think this is linked to this issue: https://github.com/openseadragon/openseadragon/issues/2415.

If you take a look in the info.json in your example: https://hrc.contentdm.oclc.org/digital/iiif/p15878coll17/8057/info.json, you'll see that the sizes are ordered in descending rather than ascending order. The extra sort() added to resolve the previous issue (https://github.com/openseadragon/openseadragon/commit/b92a428e88730546058bf9890aa44061ca370eb5) should fix this.

**Comment by craigberry** [comment] 2023-10-18 11:27
Thanks.  I can confirm that the sort changes in b92a428e8873 fixed the scaling problem in my reproducer.

**Comment by iangilman** [comment] 2023-11-06 17:30
Fixed by https://github.com/openseadragon/openseadragon/pull/2416. @craigberry Thank you for testing it!

**Closed by iangilman** 2023-11-06 17:30 UTC
