### ISSUE TITLE
Visible lines on Firefox and Safari

### ISSUE THREAD

**Issue by reneweteling** [openseadragon/openseadragon#1300] opened 2017-08-30 07:58 UTC
Hi,

I'm having some problems with Firefox and Safari, when I drag the canvas there are some squares visible. They look like the sides of the slices deepzoom images to me. I've made a small screen recording hoping this will clarify the issue. 

![lines firefox](https://user-images.githubusercontent.com/3830933/29861432-83de4c94-8d69-11e7-87c5-1c34b4b5de07.gif)

The weird thing is that this only occurs on Safari and Firefox, on Chrome all is working as expected. 

Im at a loss here, thanks!!

**Comment by iangilman** [comment] 2017-08-30 17:14
Great screen recording; really captures the issue. 

I believe this is due to rounding errors in those browser's implementations of Canvas. This is why tile overlap was added to the DZI format. What format are you using? Can you try rebuilding your image with tile overlap? Even an overlap of 1 should be enough. 

As for how to fix it without tile overlap, it may be possible to compensate for the rounding errors (assuming that's what it is), but it'll require a deep dive into the OSD renderer.

**Comment by reneweteling** [comment] 2017-08-31 11:26
Hi @iangilman 

Ah great im using LibVips to create the DZI and I've found the overlap method. I'll let you know how it works out. 

The recording is made with a free app called http://recordit.co/ and it's free :) 

Thanks for your prompt response!

**Comment by reneweteling** [comment] 2017-08-31 11:41
Hi @iangilman 

So I've re-rendered the DZI with an overlap of 5, and i now see that the images are 264x264 instead of 256x256 and the .dzi also specifies an overlap of 5...

but the issue is still there. Is there some setting in OSD that i need to configure or something?

There is demo online just be sure to select the second color, that is the one with the overlap of 5

![image](https://user-images.githubusercontent.com/3830933/29921475-fd1b9a42-8e51-11e7-83f5-1ffbe9deafd8.png)

http://skonnecarpet.s3.amazonaws.com/demo/index.html#/

Thanks!!

**Comment by iangilman** [comment] 2017-08-31 16:57
Hmm... it looks like the seams are very consistently between repetitions of your pattern, not necessarily tile seams. Have you tried turning `debugMode` on to see where the actual tile seams are? 

Is the entire thing your showing in the viewer a single DZI image? Is it possible those seams actually appear in the image itself?

**Comment by reneweteling** [comment] 2017-09-04 08:13
Hi @iangilman , sorry for the late response, im in the middle of moving, so not able to work 40+ hrs a week. 

So i just figured out thats the lines occur on the horizontal and vertical repeat.

This is the whole image 

![image](https://user-images.githubusercontent.com/3830933/30017412-600e0a7c-9159-11e7-9006-7b038189a8ca.png)

Indeed.... almost 50G for one image, they are big. So... it has to do with the horizonal and vertical wrap

This is my current config

```javascript
window.map = this.map = OpenSeadragon({
      element: this.refs.mapCanvas,
      wrapHorizontal: true,
      wrapVertical: true,
      debugMode: false,
      showNavigationControl: false,
      minZoomLevel: 0.2,
      maxZoomLevel: 4.7,
      preserveImageSizeOnResize: true,
      gestureSettingsMouse: {
        clickToZoom: false,
        scrollToZoom: false,
        flickEnabled: false,
      },
      gestureSettingsPen:{
        flickEnabled: false,
      },
      gestureSettingsUnknown:{
        flickEnabled: false,
      },
      gestureSettingsTouch: {
        flickEnabled: false,
        pinchToZoom: false, 
        flickEnabled: false,
      }
    });
```

Is there a hidden overlap feature for the wrapping capability?

Thanks!!

**Comment by iangilman** [comment] 2017-09-05 17:04
I see! That narrows it down. The first thing to look for it some sort of rounding issue with the wrap code. The `Math.floor` calls in this area seem like a good possibility: 

https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L1112

Perhaps you could try removing the four `floor` calls there and see what happens...

**Comment by reneweteling** [comment] 2017-09-06 12:05
Hi @iangilman,

So ive been debuging with the _getCornerTiles method, only this doesn't seem to be the issue. The rounding takes place at a hreally high level. so this looks correct. 

Any other ideas?

Thanks!

**Comment by iangilman** [comment] 2017-09-06 17:28
So changing the `floor` call doesn't have any effect? Or it's the wrong effect? 

I guess look for other spots that reference `wrapHorizontal` or `wrapVertical`? Also try manually shifting things over a little by adding a pixel or something for each wrap (not that that's the ultimate solution, but it might help shed some light).

**Comment by avandecreme** [comment] 2017-09-07 07:43
Thinking of it, we consider that there is no overlap when wrapping. Maybe that should be an option?

**Comment by reneweteling** [comment] 2017-09-07 12:27
Hi @iangilman,

yeah it was the wrong effect, ive looked at the wrapHorizontal methods and where they are used. and my best guess is that there is no overlap. So @avandecreme you are totally right, could you consider this?

And this probably means that the DZ image needs to have an overlap in the source file that OpenseaDragon crops off right?

We are in the middle of creating an app with extremely big images +/- 50G per image, thus far we got 24 images. So this solution will have some impact on our side. Nothing we can't handle, but it isn't great. 

My client is a bit punctual about this issue, so if there is something that i can do to expedite this issue? Bounty / Man hours? I'm all ears.

Thanks guys!

**Comment by selko** [comment] 2017-09-07 16:26
What kind of images are this? Wow, really incredible of image size. I saw your example before and i think that it's so much size for this kind of image.

How do you compose this image? Perhaps the problem is when you are composing this images. 

I work with other kind of images with a viewer and there are these sizes of images but not all of them. I had some problems like this, but i used python and other libraries.

**Comment by iangilman** [comment] 2017-09-07 17:05
I think the wrapping seams/overlap should be unrelated to whether your DZI has overlap in it. The DZI overlap is always only internal. 

I think we should try to make the seams just not appear in a wrapping scenario, but if necessary we could include some sort of seam adjustment variable.

**Comment by reneweteling** [comment] 2017-09-08 15:08
Hey Guys,

Great to see that this issue is getting so much attention. 

@selko the images are raw images that's why the source image is so big, but the input image that i use to create the DZ is this one: [source image, 500mb](https://worker.skonne.com/data/pattern-2/combined.png) that image is at 50% of the original and its a PNG instead of a RAW Tiff, the tiff is used to create the carpets and that works without seems so that's fine. 

@iangilman good to hear that the overlap isn't something that needs to be embedded in the images this will result in an angry client :)

So what about resolving the issue, how can i help? Im clueueless about what you guys charge but id be happy to spend some money to get this resolved quickly?

Thanks so much guys!

**Comment by iangilman** [comment] 2017-09-08 21:08
We don't really have a standard bounty system here, but I've worked something out with @reneweteling and I've dug into the issue. I wonder, maybe we should set up some sort of bounty system to encourage more involvement and bug fixing? Thoughts, anyone?

Anyway, I've made a fix in this pull request: #1305. @reneweteling can you please build that branch and verify that it fixes your issue?

**Comment by selko** [comment] 2017-09-09 11:21
I can help too. A bounty system could be
nice too. I think it's a good idea for resolving major fixes.

**Comment by reneweteling** [comment] 2017-09-11 06:16
@iangilman on it :)

**Comment by iangilman** [comment] 2017-09-11 16:53
@selko Cool... I've started a new issue for discussing the possibility in general: #1307

**Closed** 2017-09-15 04:19 UTC
Labels: bug

**Comment by AsmaAq** [comment] 2019-07-22 11:50
Hi @iangilman 

I had the same issue where a white lines appear on the image on FF. Any update on this or how can we resolve it?

Btw I'm using openseadragon 2.4.0

Thanks,

**Comment by iangilman** [comment] 2019-07-22 22:19
@AsmaAq Hmm... Looks like this was fixed in #1305 which shipped with Version 2.3.1. Looks like there was another follow-up (#1470) that shipped in 2.4.0. Sounds like you've found a new issue. Can you file a new issue for it and share some additional info?

**Comment by AsmaAq** [comment] 2019-07-23 06:06
@iangilman I've created a new issue

https://github.com/openseadragon/openseadragon/issues/1683

Can you please check the details there?

Thanks for the help!

**Comment by iangilman** [comment] 2019-07-23 20:31
Perfect, thanks!
