### ISSUE TITLE
How to disable "zoom out" on two finger tap on trackpad

### ISSUE THREAD

**Issue by Kampii** [openseadragon/openseadragon#947] opened 2016-05-26 00:42 UTC
I plaid with these [Gesture Settings](https://openseadragon.github.io/docs/OpenSeadragon.html#GestureSettings) but was not able to find one that would disable this behavior.

**Comment by iangilman** [comment] 2016-05-26 16:24
I'm not experiencing that behavior... let me make sure I understand: You're on an OpenSeadragon viewer, for instance http://openseadragon.github.io/ on a desktop browser and you have a trackpad connected to your computer and you move the mouse cursor over the viewer and then tap once with two fingers simultaneously and the viewer zooms out? What browser/OS are you on? Does your trackpad have any special settings?

I'm not aware of this being a feature of OpenSeadragon.

**Comment by Kampii** [comment] 2016-05-27 01:09
Please see [this video](https://youtu.be/qx4o-yTd8dU). I use chrome browser on Mac.

I'll check out if there are any Mac settings that may affect this.

**Comment by Kampii** [comment] 2016-05-27 01:35
I just discovered that if I remove the "wheel openseadragon-canvas" event listener (see the screenshot), then the two finger touch zoom out behaviour disapears along with the ability to zoom in/out by sliding two fingers to front and back on the trackpad. What would this mean?

![image](https://cloud.githubusercontent.com/assets/725316/15595026/3701f7d6-2370-11e6-9c26-d96e62b45011.png)

**Comment by iangilman** [comment] 2016-05-27 16:28
Interesting! Well, with the Mac trackpad, the two finger drag translates to scroll wheel events in the browser, which OpenSeadragon uses for zooming. I guess somehow when you tap with two fingers, the trackpad sends out a scroll event. I don't know if that's a setting on your Mac, or if it's registering some slight movement of your fingers or what. I have a Mac with an external trackpad, and I don't get the same effect. 

If you want to disable this, it seems you'll have to kill the scroll handling entirely. Setting the zoomPerScroll option to 1 is the easiest way. 

My recommendation is not to worry about it, though... This is the first I've heard of it, so your users probably aren't experiencing it.

**Comment by Kampii** [comment] 2016-05-27 16:50
Thanks! Well I deffinitely want to keep the two finger drag for zooming because it is sooo easy. I'll test this one some other Mac as well to figure out what have I messed up in my system. :)

**Comment by Kampii** [comment] 2016-05-29 02:31
I checked on another Mac and I get the same behavior in Chrome. I don't get that in Safary or Firefox. 

I did notice that it zooms out once when I first touch with two fingers, and then it zooms out if I release both fingers. Are there any ways/ workarounds to improve this?

**Comment by iangilman** [comment] 2016-06-02 16:59
Sure enough, I can reproduce it on http://openseadragon.github.io/ with Mac Chrome. Very odd. Since it only happens on Chrome, it seems to be bogus behavior on the part of the browser. Still would be nice to work around it if we could. Would you be up for taking a look at possibly fixing it?

I guess the first step would be looking at the events the browser sends during that scenario... is it really sending scroll events? Is there something special about those scroll events that could help us identify them being bogus? 

This might be a good spot to add some logging: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2841

The `event` should have an `originalEvent` property with the actual event that came from the browser.

**Comment by Kampii** [comment] 2016-06-06 03:27
Thank you for the guidelines, will check!

**Comment by Kampii** [comment] 2016-06-07 00:09
@iangilman with a help of @bayucandra below you can see some data that we get every time it touch the trackpad with two fingers, and also every time I release them. Does that tell you anything?

{"eventSource":
   {"hash":0.3176791778931356,"element":{},
   "clickTimeThreshold":300,
   "clickDistThreshold":5,
   "dblClickTimeThreshold":300,
   "dblClickDistThreshold":20,
   "userData":null,
   "stopDelay":50,
   "moveHandler":null,
   "stopHandler":null,
   "keyUpHandler":null,
   "focusHandler":null,
   "blurHandler":null},
   "pointerType":"mouse",
"position":{"x":681,"y":538},
"scroll":-1,
"shift":false,
"isTouchEvent":false,
"originalEvent":{"isTrusted":true},
"preventDefaultAction":false,
"userData":null}

**Comment by bayucandra** [comment] 2016-06-07 11:40
I also have same problem at linux machine. Seem because linux also do scrolling with double finger drag up and down. Can we reduce the sensitivity of the double finger touch to not consider it as scrolling action when just tap or very small drag with two finger?

**Comment by iangilman** [comment] 2016-06-07 16:23
Is the originalEvent really just that one property? That's the thing we want to look at, to see if there's something in what we get from the browser that can help us distinguish them. If at this level we're not actually getting an originalEvent we should travel up the chain to: 

https://github.com/openseadragon/openseadragon/blob/master/src/mousetracker.js#L1722

Take a look at both `event` and `originalEvent` in that function to get the whole picture... see: 

https://github.com/openseadragon/openseadragon/blob/master/src/mousetracker.js#L1687

... for more info; I don't offhand know if that's the handler for Chrome or if this is: 

https://github.com/openseadragon/openseadragon/blob/master/src/mousetracker.js#L1676

Anyway, one possible culprit might be this line: 

https://github.com/openseadragon/openseadragon/blob/master/src/mousetracker.js#L1731

It's possible we're getting some really small deltaY in this case and it's getting translated all the way up to -1 inappropriately. Maybe we just need to add a threshold. 

Also see that TODO comment. 

Thank you both for looking into it!

**Comment by bayucandra** [comment] 2016-06-13 10:36
Hi @iangilman , yes i is only one property for originalEvent, same property too at my linux machine with firefox and chrome. 

I have trying to get on console from function : `handleWheelEvent( tracker, event, originalEvent )`, and here is the result when the `-1` scroll occured:
For `event` it give this : `{"isTrusted":true}`
For `originalEvent` also give : `{"isTrusted":true}`

Please see attached screenshot below of log which produce by following code:
`console.log( JSON.stringify(event));`
`console.log( JSON.stringify(originalEvent));`

![160613](https://cloud.githubusercontent.com/assets/6956706/16004671/18fda908-318d-11e6-9215-e1d67410d35f.jpg)

**Comment by iangilman** [comment] 2016-06-13 23:33
Thank you! Well, 3 is a bigger value than I was hoping; seems like it's a legitimate scroll value. What kind of deltaY do you get if you actually move your two fingers (which should give the kind of scroll events we want, rather than the bogus one we're trying to filter out)? How about the other properties? Is there any way to distinguish between the bogus event and legitimate ones?

**Comment by bayucandra** [comment] 2016-06-14 02:13
I am afraid you are right :( , on drag up with double finger for zoom out, it is give me deltaY 3 too. Almost no difference between real drag up with double finger and the double tap event. The only difference about some coordinate or pixel sizes which i am not so sure what it is mean. Seem to me like the size of canvas area or viewport or something. 

Please see attached screenshot below of the double finger scroll up event, i hope you have some idea about it :)

![160614](https://cloud.githubusercontent.com/assets/6956706/16028969/f5d11460-320e-11e6-8f3c-9484c76c03e2.jpg)

**Comment by iangilman** [comment] 2016-06-14 16:54
Yes, disappointing. 

Well, maybe we need to look outside the event for other events that happen in the sequence. There should be a mousedown right before the two finger tap version of the wheel event... maybe we should ignore any wheel event directly after a mousedown?

BTW, this bogus wheel event seems like it's not specific to OSD, right? So if it's helpful for your investigation, you could make a non-OSD test that just uses jQuery or raw JavaScript... just a thought. 

Also it might be interesting to see if anyone's reported it as a bug with Chrome and if there's any discussion there about mitigating.

**Comment by bayucandra** [comment] 2016-06-16 05:34
After some test with simple javascript on `mousewheel` event, i must agree that this issue is not specific to OSD. It is give me same event for both mouse scroll and when `double finger tap` triggering the `double finger drag up`.
Anyway, thanks for your guide to make me clear about this issue.
@Kampii : seem we have no way to handle this since this is an OS interface issue which is not related to OSD issue.

**Comment by Kampii** [comment] 2016-06-16 09:07
Well, it is good and bad :)

**Comment by Kampii** [comment] 2016-08-23 03:33
I was just using google maps to find a certain location when I realized that double finger tap does not trigger zoom out event which was kind of surprising. I am wondering if there is still a way to improve this.

**Comment by iangilman** [comment] 2016-08-23 16:35
@Kampii Great discovery! It must be possible then!

One thing I notice is that Google Maps has its own context menu that comes up in response to the two-finger tap. OSD, on the other hand, just gives you the standard browser menu. Maybe the trick is to capture right click events and stop them.

@Kampii @bayucandra Would either of you be up for experimenting with that?

**Comment by bayucandra** [comment] 2016-08-24 13:28
It has different result on my side for Google map with double finger. With Firefox on Linux i still got same problem.
@Kampii  could you try a bit more with Google maps to make sure that there is no double finger tap problem with them?

**Comment by iangilman** [comment] 2016-08-24 16:46
FWIW, I get the same result as @Kampii with Google Maps in Mac Chrome Version 52.0.2743.116.

@bayucandra Can you try on Linux Chrome? Interesting you're getting the problem in Firefox... I don't get it in Mac Firefox.

**Comment by bayucandra** [comment] 2016-08-24 16:56
@iangilman : same result with Chrome on Linux. Still zooming out. This is my chrome detail : "Version 52.0.2743.116 Built on 8.5, running on Debian 8.5 (64-bit)".
I will try to work with @Kampii to experiment with right click handling. Although i still confusing how could Mac convert scroll to a right click event. Will let you know the result later.

**Comment by bayucandra** [comment] 2016-08-25 02:07
@iangilman , we just made some experiment with right click blocking, but seem our code not work. Please find code below and please let us know if maybe it is not like what you have thinking before.

        var isNS = (navigator.appName == "Netscape") ? 1 : 0;

        if(navigator.appName == "Netscape") document.captureEvents(Event.MOUSEDOWN||Event.MOUSEUP);

        function mischandler(){
            console.log('mischandler()');
            return false;
        }

        function mousehandler(e){
            console.log('mousehandler()');
            var myevent = (isNS) ? e : event;
            var eventbutton = (isNS) ? myevent.which : myevent.button;
            if((eventbutton==2)||(eventbutton==3)) return false;
        }
        document.oncontextmenu = mischandler;
        document.onmousedown = mousehandler;
        document.onmouseup = mousehandler;

**Comment by msalsbery** [comment] 2016-08-25 02:14
Ok, I'm going to get back to work on improving the pointer event stuff...I've noticed some regression since 2.0 and I've let it slide way too long.



On Aug 24, 2016, at 7:07 PM, Bayu Candra <notifications@github.com<mailto:notifications@github.com>> wrote:


@iangilman<https://github.com/iangilman> , we just made some experiment with right click blocking, but seem our code not work. Please find code below and please let us know if maybe it is not like what you have thinking before.

    var isNS = (navigator.appName == "Netscape") ? 1 : 0;

    if(navigator.appName == "Netscape") document.captureEvents(Event.MOUSEDOWN||Event.MOUSEUP);

    function mischandler(){
        console.log('mischandler()');
        return false;
    }

    function mousehandler(e){
        console.log('mousehandler()');
        var myevent = (isNS) ? e : event;
        var eventbutton = (isNS) ? myevent.which : myevent.button;
        if((eventbutton==2)||(eventbutton==3)) return false;
    }
    document.oncontextmenu = mischandler;
    document.onmousedown = mousehandler;
    document.onmouseup = mousehandler;


-

**Comment by bayucandra** [comment] 2016-08-25 07:47
@msalsbery That sounds great. Can't wait your great improvement :). Thanks.

**Comment by iangilman** [comment] 2016-08-25 16:23
@msalsbery Wonderful! :)

**Comment by iangilman** [comment] 2016-08-25 17:53
@bayucandra Yes, your code is similar to what I was thinking. I assume that's on a page without OpenSeadragon? I've just tried a similar test:

http://codepen.io/iangilman/pen/xOoJgm

...with the same results. Google Maps must be doing something more. I wonder if there's some way to contact them?

**Comment by Kampii** [comment] 2016-10-12 19:26
@msalsbery Did you have a chance to look at what improvements could be done here?

**Comment by cavenel** [comment] 2023-10-25 07:19
I think I found a fix for this old bug!
In mousetracker.js, here: https://github.com/openseadragon/openseadragon/blob/640526b444536dccb2c78eec7a0b4b7eeb1eb43c/src/mousetracker.js#L2073
You define `nDelta` as 1 if `event.deltaY > 0`, and -1 otherwise. That means a `deltaY` of 0 will give a negative `nDelta`, resulting in a zoom out.
This has multiple side effects:
 - a horizontal scroll with a touchpad (in most browsers) will keep deltaY to 0, making it always zoom out.
 - a single double tap on a touchpad (in MacOS X and linux) will result in a wheel event with both deltaX and deltaY equal to zero, and will then zoom out.

An easy fix would be to replace:
```javascript
nDelta = event.deltaY < 0 ? 1 : -1;
```
with
```javascript
nDelta = event.deltaY ? (event.deltaY < 0 ? 1 : -1) : 0;
```
If you think that makes sense, I'll do a PR.

**Closed** 2023-11-13 17:53 UTC
Labels: bug
