### ISSUE TITLE
Question: Overlap another image to the original DZI image

### ISSUE THREAD

**Issue by sickrandir** [openseadragon/openseadragon#844] opened 2016-02-11 09:34 UTC
Hi,
I'm looking to build with openseadragon an interface that let the user choose different elements (images, not vector graphics) to overlap on the original DZI image.
I looked at the features and the plugins available and I did not find something that addresses this use case, only vector graphic ones.
It's something that has already been done or it's feasible in some way?
I was also thinking of overlapping the image in the backend, generate a new DZI and reloading the tiles. Is it possible to do it?

**Comment by avandecreme** [comment] 2016-02-11 15:12
You are in luck! @altert just released 2 plugins to work with a canvas overlay:
-with fabricjs: https://github.com/altert/OpenseadragonFabricjsOverlay
-plain canvas: https://github.com/altert/OpenSeadragonCanvasOverlay

> I was also thinking of overlapping the image in the backend, generate a new DZI and reloading the tiles. Is it possible to do it?

It probably would be slower and harder to implement. That wouldn't be me first choice.

**Comment by sickrandir** [comment] 2016-02-12 08:54
Thank you very much @avandecreme!
The canvas plugin will be very useful. 
I made this small example using the canvas plugin: 
http://differenthood.duckdns.org/canvas/canvas.html
As you can see the overlapped element doesn't look that good when you are totally zoomed out. 
In this way, finer details don't leverage the zoomable image advantages.
Also if the element to overlap is larger and very defined one would have to load a big detailed image even in a zoomed out view and in that situation I can imagine it's more bandwidth efficient to load only the "low-res" tiles of the zoomed out view.
What do you think?
Is there someone who already accomplished something like that?

**Comment by avandecreme** [comment] 2016-02-12 12:54
Dowsampling is pretty low quality in the browsers. Here is a discussion about it: http://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality

However in your case, it looks like you could just use the [multi-image](http://openseadragon.github.io/examples/multi-image/) instead of the canvas plugin.
You can then just add the small image on top of the big one.
You have 2 options on how to add the image:
1. Use the [ImageTileSource](http://openseadragon.github.io/examples/tilesource-image/). We are doing a better downsampling job by default with this one. However be aware of #813 if you plan to add a lot of this images.
1. Build a pyramid before hand to enforce high quality images (might save a bit of bandwidth too)

**Comment by sickrandir** [comment] 2016-02-15 12:45
@avandecreme thanks for pointing me to the multi-image feature.
I created png tiles (with transparency) of the smaller image and overlapped it to the bigger one by using x,y values smaller than 1.
It works but the transparency of the second image doesn't work, as you can see here: 
http://differenthood.duckdns.org/canvas/multi.html
Is it something that depends on the tiles or on some option in openseadragon?
Thanks again.

**Comment by avandecreme** [comment] 2016-02-15 12:53
It looks like your png tiles have a white background. See http://differenthood.duckdns.org/canvas/dzi/borchia_files/6/0_0.png
Maybe your pyramid builder is not generating them correctly?

**Comment by sickrandir** [comment] 2016-02-15 13:24
It's strange. I see the PNGs as transparent backgrounf files. I also tried to open the same link you pasted with pixlr (https://pixlr.com/editor/) and it shows the png with transparent background.
However that doesn't happen in openseadragon.

**Comment by avandecreme** [comment] 2016-02-15 13:36
Intersting, on Firefox it looks like the tile is not transparent but it actually is.
So I think, we might have a bug in OSD.
Could you try to add an opacity of 0.99 to the small image like this:

```javascript
                    this.viewer.addTiledImage({
                        tileSource: 'dzi/borchia.dzi',
                        x: 0.33,
                        y: 0.43,
                        width: 0.05,
                        opacity: 0.99
                    });
```

**Comment by sickrandir** [comment] 2016-02-15 14:04
It works! Adding opacity: 0.99 made it work.
Thank you. 
Since I'll probably have some small question like this in future. Should I ask them here or find you in IRC or something else?
Thanks again.

**Comment by avandecreme** [comment] 2016-02-15 14:40
Here is fine. You can also ask on [gitter](https://gitter.im/openseadragon/openseadragon).

**Comment by iangilman** [comment] 2016-02-16 17:44
@avandecreme Interesting...so we have a bug with drawing PNGs with transparency? What would you say the cause is? Can you file an issue for it?

**Comment by avandecreme** [comment] 2016-02-16 17:46
Yes, I already filed issue #849 about it.

**Comment by iangilman** [comment] 2016-02-16 18:20
Nice! Way ahead of me :)

**Comment by avandecreme** [comment] 2016-02-25 17:51
@sickrandir This is now fixed on master.

**Closed** 2016-02-29 17:30 UTC
Labels: question
