### ISSUE TITLE
serialized initial tile loads

### ISSUE THREAD

**Issue by chris-cooper** [openseadragon/openseadragon#1048] opened 2016-10-10 03:04 UTC
I'm finding that initial tile loads of a single deep zoom image seem to be serialized.  I tried experimenting with the imageLoaderLimit option but it didn't seem to help.  Is there something I'm doing wrong?  My initial setup looks like this...

```
        this.viewer = new OpenSeadragon({
            defaultZoomLevel: defaultZoomLevel,
            id: this.domElement.id,
            imageLoaderLimit: 24,
            immediateRender: true,
            prefixUrl: "/static/images/",
            showHomeControl: false,
            tileSources: url,
        })
```
Here is a screenshot from Chrome's network tab.  Since green is latency the performance is much worse than it could be (particularly with HTTP2 or domain sharding).  All tiles are from level 10 due to the immediateRender flag.

![image](https://cloud.githubusercontent.com/assets/484870/19226064/ddd55322-8ef1-11e6-9a84-915b9ceb3832.png)

**Comment by avandecreme** [comment] 2016-10-10 10:46
This is a duplicate of #1013 which has been fixed on master.
However, be aware of #1020.

**Closed by avandecreme** 2016-10-10 10:46 UTC
