### ISSUE TITLE
`timeout` option set on viewer does not seem to have an effect

### ISSUE THREAD

**Issue by jrochkind** [openseadragon/openseadragon#1279] opened 2017-08-03 18:23 UTC
I passed a timeout: 10, expecting timeout errors, but didn't get any. Confirmed in chrome dev tools that tiles fetched were not being fetched from cache, and did take more than 10ms to fetch.

Setting `OpenSeadragon.DEFAULT_SETTINGS.timeout = 10;` did trigger the timeouts I expected. So that global setting does work to override timeout. But passing timeout as option to Openseadragon() viewer creation does not seem to. 

Have not yet tried to trace the code to figure out what's going on. 

One thing that would make things more transparent is if the timeout errors printed to console also included the timeout value, so you at least knew what timeout value it was working with. Probably useful for debugging even if this is fixed.

**Comment by markmatney** [comment] 2018-09-10 08:13
Hi @jrochkind, can you check out https://github.com/UCLALibrary/openseadragon/tree/timeout-configuration, run `grunt dev`, then go to http://localhost:8000/test/demo/timeout-certain.html and http://localhost:8000/test/demo/timeout-unlikely.html and let me know what happens?

**Comment by jrochkind** [comment] 2018-09-11 14:41
@markmatney thanks for providing such clear request, and I'd like to help -- but I'm afraid I'm not familiar with grunt. I tried installing grunt, but when I run `grunt dev` in a checkout of your fork on the `timeout-configuration` branch, I get:

```
$ grunt dev
grunt-cli: The grunt command line interface (v1.3.1)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

https://gruntjs.com/getting-started
```

I think grunt-dev needs some things you don't have checked into the branch but might have locally?

**Comment by iangilman** [comment] 2018-09-11 16:08
@jrochkind You also need to run `npm install` before running `grunt dev`. See https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md for more info.

**Comment by jrochkind** [comment] 2018-09-11 16:30
timeout-unlikely does what I think is expected -- shows an OSD interface. 

not sure about timeout-certain. it does put a bunch of errors in console. In the browser, the OSD UI starts out appearing to show, but then flashes in and out a few times, before settling on not showing. I am thinking that is maybe expected? The console errors are there, including telling you the timeout value.

**Comment by markmatney** [comment] 2018-09-11 16:45
Sounds like those tests are working as intended. When I open `timeout-certain`, the OSD mini-map in the top-right corner appears to load, but the main viewer component does not.

Which OS and web browser are you working with?

**Comment by jrochkind** [comment] 2018-09-11 16:56
MacOS chrome. I think we're good.

**Comment by markmatney** [comment] 2018-09-12 18:47
OK to close this issue?

**Comment by jrochkind** [comment] 2018-09-12 21:05
I am no longer in a position to reproduce and provide more info on this issue from a year ago, so I can't really say if it currently reproduces or not. I don't currently have time/priority to try to reproduce it myself. So I dunno, do what you think is best? If you can't reproduce it, I guess it makes sense to close it?  Or if you have no time to try and reproduce it either, I guess that's how the cookie crumbles!

**Comment by markmatney** [comment] 2018-09-12 21:30
Looking at the date that this issue was filed (Aug. 3, 2017), you must have been using no later than the [0.3.3 rubygem](https://rubygems.org/gems/openseadragon/versions/0.3.3), so the OSD in question is  [2.2.1](https://github.com/cbeer/openseadragon-rails/blob/v0.3.3/vendor/assets/javascripts/openseadragon/openseadragon.js) or earlier (before #1192).

Based on that, and your report of the behavior of `test-certain` and `test-unlikely`, I'm confident this can be closed.

**Closed** 2018-09-12 21:31 UTC
Labels: bug

**Comment by iangilman** [comment] 2018-09-13 16:09
Awesome... Thank you for following up on this!
