### ISSUE TITLE
Force OSD to continue loading lower levels

### ISSUE THREAD

**Issue by bdrichards** [openseadragon/openseadragon#913] opened 2016-04-17 00:09 UTC
After reading through all the API docs about the "options", the viewer, and the viewport I can't seem to understand the following issue:
OSD seems to stop loading lower levels and stops at the resolution indicated in this screen capture:

![osd01](https://cloud.githubusercontent.com/assets/18133188/14584309/6fdc2206-03f5-11e6-9a3a-76f2f57a9551.JPG)

HOWEVER, it is supposed to resolve to this level:
![osd02](https://cloud.githubusercontent.com/assets/18133188/14584314/dd903f1c-03f5-11e6-9a68-09f56cecddd3.JPG)

What "settings", or options are controlling this behavior?

**Comment by iangilman** [comment] 2016-04-18 16:43
Hmm, it should just work. Are you getting any errors in the console? Do you have a link to the page you can share?

**Comment by bdrichards** [comment] 2016-04-20 02:27
Here is a screencapture showing the error(S) shown in the console:
(the link is: [http://coursecontent.nic.edu/bdrichards/gigapixelimages/dryfalls])

![osdcapture](https://cloud.githubusercontent.com/assets/18133188/14661669/5801a28e-0664-11e6-8571-005bfd42b2a6.JPG)

**Comment by avandecreme** [comment] 2016-04-20 11:57
It looks like that there is some network issues. I reproduced it randomly.
You can try to increase the timeout but it is already set at 30000ms by default which is already quite long.

@iangilman it looks like the only way to change the timeout is to set:
```javascript
OpenSeadragon.DEFAULT_SETTINGS.timeout = 60000;
```
See https://github.com/openseadragon/openseadragon/blob/master/src/imageloader.js#L41

**Comment by iangilman** [comment] 2016-04-20 17:00
@avandecreme Interesting... we should probably expose that in the construction options at some point. 

@bdrichards Is there anything you can do to speed up that server? I suppose one possibility is that it doesn't like being hit with so many simultaneous requests. You can try something like `imageLoaderLimit: 4` in the options when you create your viewer. Great image, BTW!

**Comment by bdrichards** [comment] 2016-04-20 17:36
@iangilman  Thanks for the insights and having a look at my "virtual field-trip". The imageLoaderLimit setting is the next thing to test. I currently set the options as shown below which includes setting the timeout option to 1000000 (does not seem to help). I will speak with the network engineer, the server is a virtual machine on our campus system with tons of resources and "... 1Gbps internet that supplies plenty of outgoing bandwidth." according to the engineer; however, the server is likely not setup anyway as an "image" server. The issue NEVER occurs when I am testing on campus (connected to the same network, duh).
Here are my viewer options
```
    var viewer = OpenSeadragon({
        id: "openseadragon1",
                showNavigator: true,        
       prefixUrl : "/bdrichards/gigapixelimages/openseadragon/images/",
        controlsFadeLength: 650,
        //maxZoomLevel: 50,
       maxZoomPixelRatio: Infinity,
       minPixelRatio: 0.15,
       preserveImageSizeOnResize: true,
       maxImageCacheCount: 500,
       timeout: 1000000, // default is 30000
       placeholderFillStyle: "#AAAAAA",
        tileSources: {
	        Image: {
	            xmlns:    "http://schemas.microsoft.com/deepzoom/2008",
	            Url:      "dryfalls02_156604x13548-copy01_files/",
	            Format:   "png", 
	            Overlap:  "1", 
	            TileSize: "254",
	            Size: {
	                Height: "13548",
	                Width:  "156604"
	            }
	        }
	    }
    });

```

**Comment by iangilman** [comment] 2016-04-21 22:24
Cool, let me know how imageLoaderLimit treats you. You might also try doing something different for minPixelRatio; the setting of 0.15 will make it especially aggressive about loading new tiles. 

@avandecreme Looks like `timeout` can be used in the options after all. The code you pointed to is just setting up defaults, but the options override it. Is there something else you spotted?

**Comment by avandecreme** [comment] 2016-04-21 22:27
The options are set here: https://github.com/openseadragon/openseadragon/blob/master/src/imageloader.js#L128-L134
I don't see `timeout` set.

**Comment by bdrichards** [comment] 2016-04-22 01:52
@avandecreme  I have set the `timeout:` option during viewer creation (maybe this doesn't actually change the value?)
@iangilman Changing the the imageLoaderLimit option to something between 4 and 7 helps **_tremendously_** and our network engineer will look at a few settings/policies on the server for me. My colleagues may be using a VPN connection from their homes to access their campus accounts, from which they are accessing my images, which will totally kill their bandwidth.
Here is another image (of an iconic North America landmark) that was giving fits, but is now improved - how many climbers can you find? [DevilsTower](http://coursecontent.nic.edu/bdrichards/gigapixelimages/devilstower01)

**Comment by avandecreme** [comment] 2016-04-22 13:21
> @avandecreme I have set the timeout: option during viewer creation (maybe this doesn't actually change the value?)

Yeah I don't think that actually work. However setting the imageLoaderLimit seems like a better option.
I wonder if increasing the tile size (by regenerating the image with a tile size of 510 for example) could help as well?

Very nice images :+1:

**Comment by iangilman** [comment] 2016-04-22 17:02
@avandecreme I stand corrected! So, to fix the timeout option it would need to get passed from the Viewer into the ImageLoader and from there into the individual jobs. Seems worth fixing (or, I guess removing the `timeout` option from the docs). I agree using it is not the fix for this issue though... glad to hear imageLoaderLimit is working well. 

I agree that regenerating the image with tile size of 510 is also a good idea. I guess it might be worth updating our "creating images" page with that recommendation across the board. 

@bdrichards Another great photo! When you're ready, we can add these to our "in the wild" page.

**Comment by jrochkind** [comment] 2017-07-31 20:39
Is there currently any way to set the image loading timeout, the one that results in "error: Image load exceeded timeout" in the console?  If I'm reading this issue right, there is currently no way to do it at all? But it defaults to 30 seconds?

**Comment by jrochkind** [comment] 2017-07-31 20:41
default seems to be way less than 30 seconds.

**Comment by iangilman** [comment] 2017-08-01 20:00
Hmm... looking at the code now, it seems that the `timeout` option should be getting honored. It's passed from the Viewer into the ImageLoader here:

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L380

...and from the ImageLoader into the ImageJob here:

https://github.com/openseadragon/openseadragon/blob/master/src/imageloader.js#L217

...and used by the ImageJob here: 

https://github.com/openseadragon/openseadragon/blob/master/src/imageloader.js#L89

@jrochkind Can you give it a try to see if it works? Also, if the default is less than 30 seconds for you, can you quantify it somehow?

**Comment by jrochkind** [comment] 2017-08-01 20:48
actually trying to reproduce, i am getting timeouts at about 30s that might have been a false alarm. will continue to investigate and update if i find anything odd.

**Comment by iangilman** [comment] 2017-08-02 17:05
Good to hear the 30 seconds thing was a false alarm. Let me know if you get the `timeout` option to work. :)

**Comment by jrochkind** [comment] 2017-08-03 14:20
@iangilman I am not certain timeout from viewer is really being passed on. I passed a `timeout: 10`, expecting timeout errors, but didn't get any.  Confirmed in chrome dev tools that tiles fetched were not being fetched from cache, and did take more than 10ms to fetch. 

Setting `OpenSeadragon.DEFAULT_SETTINGS.timeout = 10;` _did_ trigger the timeouts I expected. So that global setting does work to override timeout. But passing `timeout` as option to `Openseadragon()` viewer creation does not seem to.  Would you like me to file a separate issue?

**Comment by iangilman** [comment] 2017-08-03 18:06
Yeah, probably creating a new issue for that would be good. Also if you'd like to trace down the issue and create a pull request for it, that would be lovely as well :)

**Comment by iangilman** [comment] 2017-08-04 17:05
@jrochkind Thank you for filing the new issue. Closing this now in favor of #1279.

**Closed by iangilman** 2017-08-04 17:05 UTC
Labels: enhancement, question
