### ISSUE TITLE
Touch interactions stop working if useCanvas = false

### ISSUE THREAD

**Issue by wesleyfok** [openseadragon/openseadragon#539] opened 2014-12-10 16:20 UTC
As a caveat, I'm using the collections branch right now, so this might not apply to the main branch.

If I turn off useCanvas and then attempt to use OpenSeadragon in either Chrome for Android (Android 5.0.0, Chrome 39.0.2171.93, Nexus 5) or Safari for iOS (don't have the device on me now but it's iOS 8, iPhone 6), touch interactions will eventually stop working. Panning around the image collection works fine and doesn't appear to break anything, but if you start using pinch-to-zoom, the image area will eventually stop accepting touch input. The amount of pinch does seem to affect the number of pinch actions you can perform before touch input stops working, but I can't discern a particular relationship.

Using the toolbar buttons still works to zoom in/out. It doesn't have panning controls so I haven't checked to see if panning still works but my guess is it does. After poking around in the code, I think the issue might be in how touch contact points are stored. Debugging via Chrome shows that touch input seems to break when the GesturePointList for touch contacts shows FOUR contacts instead of two; at that point, updatePointersMove() doesn't seem to know what to do and instead does nothing. I don't know why the GesturePointList suddenly doubles the number of actual touch points or why this only seems to happen when useCanvas is set to false.

(As an aside, I'm setting useCanvas to false because on high-dpi screens, the canvas implementation is very pixelated even if I try to force it to use retina-density images. Perhaps I should file a separate issue for this?)

**Comment by msalsbery** [comment] 2015-01-15 20:26
Fixed by #566 

It's unknown what the problem is on Webkit, but it seems the combination of touch events and rapidly changing DOM (lots of div elements when useCanvas == false!) causes it to choke. Mouse events seem to work fine.

Since the crash can't be detected (touch events simply stop firing), I just abort all tracked touch events if a discrepancy is detected. This at least allows the user to continue navigating with subsequent touch contacts.

The real fix is to use useCanvas = true :)

**Closed** 2015-01-16 18:23 UTC
Labels: bug
