### ISSUE TITLE
IE panning

### ISSUE THREAD

**Issue by hossam707** [openseadragon/openseadragon#933] opened 2016-05-03 11:40 UTC
Sometimes I face a problem with panning in internet explorer running from web browser control in C# as it often do panning with only mouse move without pressing mouse down.

**Comment by avandecreme** [comment] 2016-05-06 14:11
It sounds like a bug with the web browser control not raising the `mousedown` event. Have you tried looking for a reason for that?

**Comment by hossam707** [comment] 2016-05-06 15:14
I faced this problem also with internet explorer browser as it sometimes not capture mouse up event so it continues panning forever

**Comment by hossam707** [comment] 2016-05-09 08:14
any help please?

**Comment by avandecreme** [comment] 2016-05-09 13:37
Do you reproduce it on http://openseadragon.github.io as well?

**Comment by hossam707** [comment] 2016-05-10 19:54
yes but after panning for some time.

**Comment by avandecreme** [comment] 2016-05-10 20:10
What version of IE are you using? I am not able to reproduce it with IE11.

**Comment by hossam707** [comment] 2016-05-12 11:35
you can reproduce it using web browser control in c# which will use IE8.

**Comment by avandecreme** [comment] 2016-05-12 13:35
Have you tried to force a more recent version of IE as I suggested in #920 ?
Here is the link on how to do that: https://blogs.msdn.microsoft.com/patricka/2015/01/12/controlling-webbrowser-control-compatibility/

**Comment by hossam707** [comment] 2016-05-12 22:23
yes I tried this already.

**Comment by avandecreme** [comment] 2016-05-12 23:39
What was the result? Were you able to force IE11?

**Comment by hossam707** [comment] 2016-05-13 08:58
I will try to publish my website and give you an exe to test it soon and
thanks for your care

**Comment by hossam707** [comment] 2016-05-15 07:06
you can test this exe : https://www.dropbox.com/s/4tciej5d8mpboi6/OSDViewer.rar?dl=0

**Comment by avandecreme** [comment] 2016-05-15 20:13
Sorry, I only have a Linux machine. I can't help you with that.
Plus, it wouldn't be safe to run an unknown executable on my machine...

**Comment by hossam707** [comment] 2016-05-16 06:37
Ok never mind.

**Comment by msalsbery** [comment] 2020-07-26 04:32
Should be fixed in my next patch (v.2.4.3 or possibly 2.5.0), assigning to myself

**Comment by msalsbery** [comment] 2020-08-13 18:07
@hossam707 

I know this is an OLD issue, but I'm finishing up an event-handling (MouseTracker) patch and I'm curious if the new code improves the issues you're seeing (it should!).

If you have a little time to try it out, I would love to hear your feedback!

[Links to Demos and Preview Builds](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)

Cheers

**Comment by msalsbery** [comment] 2021-03-09 19:13
IE < 11 no longer supported as of #1949

New overhauled pointer-events (MouseTracker) code for v2.5.0 (#1872)

Closing this...Feel free to reopen if issue persists!

**Closed by msalsbery** 2021-03-09 19:13 UTC
Labels: bug
