### ISSUE TITLE
Deepest Level Image Disappears for mobile

### ISSUE THREAD

**Issue by jiafuchen** [openseadragon/openseadragon#559] opened 2015-01-08 20:53 UTC
Dear All,
My name is Jiafu and I am a  web developer.Recently I implemented the openseadragon plugin into my site. Everything is working perfectly on desktops.For mobile devices(IOS), however, when I zoom the image into the biggest size, the image disappears,showing only white space inside the canvas.
BTW, I am using legacy image pyramids solution,which allows me to use existing images of different sizes without having to pregenerate image tiles.See https://openseadragon.github.io/examples/tilesource-legacy/
Has anyone experienced similar issues when using mobile devices.Thanks a lot!

**Comment by msalsbery** [comment] 2015-01-08 21:18
Yes I've seen it happen on that site using my iPhone.

My first thought was that it's a tile source configuration issue - maybe maxLevel needs to be set? I haven't looked into the tile source yet to see...

**Comment by jiafuchen** [comment] 2015-01-08 21:21
Thanks Mark.I think it's caused by resource limit of IOS.
I found it reported in a previous post: https://github.com/openseadragon/openseadragon/issues/381
I will try the solutions on it and hopefully it works. Thanks!

**Comment by iangilman** [comment] 2015-01-09 17:18
Closing as a duplicate of #381

**Closed by iangilman** 2015-01-09 17:18 UTC
