### ISSUE TITLE
After calling panTo and zoomTo in iOS Webview, the animation becomes very stuck

### ISSUE THREAD

**Issue by q990724** [openseadragon/openseadragon#1867] opened 2020-08-05 03:39 UTC
I opened a web site in the webview of iOS. The web page uses openseadragon, and there are several tabs at the bottom of the web page. After each tab is clicked, panTo and zoomTo are called to the specified location, and then the gesture is moved/zoomed. The animation becomes very stuck

**Comment by msalsbery** [comment] 2020-08-05 04:30
@q990724 Is the site accessible publicly?

**Comment by q990724** [comment] 2020-08-05 05:49
@msalsbery I opened https://openseadragon.github.io/ in Safari on iPhone7 Plus iOS13.3.1, and the official Demo animation is also very stuck.

**Comment by msalsbery** [comment] 2020-08-05 16:04
@q990724  hmm, I don't see anything weird going on...what do you mean by "_The animation becomes very stuck_"?

**Comment by q990724** [comment] 2020-08-06 01:19
@msalsbery Scaling and moving are not smooth in safari   iOS13.3.1 iPhone7Plus

**Comment by iangilman** [comment] 2020-08-06 17:04
Hmm, I can't reproduce on iOS 13.4.1 Safari on an iPhone 8. I went to https://openseadragon.github.io/ and panned and zoomed, and it seemed fine.

I wonder what the differences that's causing the issue.

**Comment by iangilman** [comment] 2020-08-06 17:06
A possibly related issue: https://github.com/openseadragon/openseadragon/issues/1753

**Comment by msalsbery** [comment] 2020-08-06 18:01
iPhone 7, iOS 13.6 seeing no issues as well...hmm...

**Comment by peili** [comment] 2020-08-07 23:37
> iPhone 7, iOS 13.6 seeing no issues as well...hmm...

I can reproduce the issue on an iPhone XS, iOS 13.6
You need go activate „Fullscreen“ mode.

**Comment by iangilman** [comment] 2020-08-12 22:25
OK, on the homepage in full screen mode on an iPhone it does seem like the frame rate isn't super high. I wouldn't call it "very stuck", just not "buttery smooth".

One factor on our home page is that it's not mobile responsive, so it's actually a full-sized desktop homepage scaled down on your phone. That might be one reason for the low frame rate there. I've filed issue https://github.com/openseadragon/site-build/issues/226 to discuss that further.

Anyway, I'm not sure we've gotten to a repro for the "very stuck" described in the issue title here…

**Comment by msalsbery** [comment] 2020-08-12 23:27
> Anyway, I'm not sure we've gotten to a repro for the "very stuck" described in the issue title here…

I’m personally waiting for the next MouseTracker patch before I look at this further...there’s several bug fixes and many improvements that may affect this. I’ll be posting at least a preview on my demo pages, links to preview builds, and of course the patch branch on the repository tonight or tomorrow (getting close!)...

**Comment by msalsbery** [comment] 2020-08-13 17:51
@q990724 

I'm finishing up an event-handling (MouseTracker) patch and I'm curious if the new code improves the user experience issues you're seeing.

If you have a little time to try it out, I would love to hear your feedback!

[Links to Demos and Preview Builds](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)

Cheers

**Comment by q990724** [comment] 2020-09-23 11:38
@msalsbery 
I'm sorry, I tested the new version and it's still the same problem.
**But I did a video this time.**
[Sample video](http://acuteberry.com/5549d7a1777c18c86a2368567c47591d.mp4)
1. At the beginning of the video, I only operated on the canvas and there was no problem.

2.  When I click a thumbnail below, I call zoomoto and panto to move the canvas to a specified location automatically. Then I operate the canvas and there is a problem (The frame rate of the whole page becomes particularly low).

3. However, when I click on another thumbnail below again, the frame rate of the picture goes up again. Unfortunately, it is only for a period of time, and then the frame rate goes down again.

Finally, thank you for your attention to the problem!

**Comment by iangilman** [comment] 2020-10-28 16:52
This is a WebView inside of a native iOS app, right? Looks like it's running on an iPad (or iPad simulator), is that correct? Is it an iPad Pro? Have you tried it on different devices? Are you able to try it in the regular iOS Safari? Does it have the same problem there?

I believe Xcode has performance logging tools… Have you tried any of those to see if it's having memory trouble or something?

**Comment by msalsbery** [comment] 2021-03-09 19:07
@q990724 

I don't think this is a pointer-events related issue, but now that #1872 has landed it may be worth retesting with the latest OpenSeadragon build...

**Comment by msalsbery** [comment] 2021-05-01 17:29
@q990724 

Also worth trying...

Try styling .openseadragon-canvas:focus to remove any default outline and see if pan/zoom performance improves, something like
```javascript
.openseadragon-canvas:focus {
  outline: none;
}
```

**Closed** 2023-02-18 18:29 UTC
Labels: question
