### ISSUE TITLE
WebGL Drawer draws TiledImage even when opacity is 0

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#2461] opened 2024-01-31 19:02 UTC
Hi there, thanks for the WebGL! 

A minor question, maybe that's only me. When I switched to the webGL build, I saw that my overlays are all tried to be loaded. They are all added with opacity = 0, which prevents OSD to actually load them. But with the WebGL drawer, the opacity seems to be 1, even if the images have been added with opacity 0.

Can this be?

**Comment by pearcetm** [comment] 2024-01-31 19:59
When I run `grunt dev` and use the drawer comparison page (http://localhost:8000/test/demo/drawercomparison.html), setting the opacity to 0 makes the image disappear like I'd expect.

Maybe there's a difference with how you're setting your viewer up. Do you have something that reproduces what you're seeing?

**Comment by pearcetm** [comment] 2024-01-31 20:02
Also, what do you mean by your overlays? How are overlay being triggered? I have a feeling that might have something to do with it. Another thing to try to get more data about this behavior would be to use the new build but with the `drawer: 'canvas'` option. Are you seeing the same thing with both drawers?

**Comment by jetic83** [comment] 2024-01-31 20:27
With overlays, I mean additional TiledImages (usually with transparent opacity, but often opacity = 0).
E.g., I load the main image, opacity = 1.
Then, I define an "overlay" image, tiledImage with source, x = 0, y = 0, width 1, height 1 (same size as the main image), and opacity = 0.
As soon, as I do viewer.addTiledImage(overlayImage), then it tries to load all the tiles, even if they are transparent and preLoad = false.
This is the case since I updated to the latest OSD version (I used a version from Nov 20, 2023 before, maybe other things have changed as well). In the ealier version, OSD would have the overlay, but only start loading the tiles when I increase the opacity.

**Comment by pearcetm** [comment] 2024-01-31 20:43
I see - looks like I overlooked that part of the prior behavior. https://github.com/openseadragon/openseadragon/pull/2462 should address it. You're welcome to build the code from that PR (or change your local copy to reflect it) and test to make sure it fixes the issue.

**Comment by jetic83** [comment] 2024-02-01 09:08
Thanks!
#2462 does not seem to solve the issue (tiles are still loaded in the background.

But, I think it has something to do with the draw function in tiledimage.js:321 (before):
```
draw: function() {
        if (this.opacity !== 0 || this._preload) {
            this._midDraw = true;
            this._updateViewport();
            this._midDraw = false;
        }
        // Images with opacity 0 should not need to be drawn in future. this._needsDraw = false is set in this._updateViewport() for other images.
        else {
            this._needsDraw = false;
        }
    },
```
`_updateViewport()` would load the tiles using `_loadTile(tile, currentTime)` and `_imageLoader.addJob()`. Allowing all opacities in the `draw` function above will result in loading tiles even with 0 opacity.

Now, this became a more complex `update` function instead of `draw` (tiledimage.js:294). Not sure if the opacity condition makes sense here still?

**Comment by jetic83** [comment] 2024-02-01 09:14
Seems like it works with

```
    update: function(viewportChanged) {
        if (this.opacity !== 0){
            let xUpdated = this._xSpring.update();
            let yUpdated = this._ySpring.update();
            let scaleUpdated = this._scaleSpring.update();
            let degreesUpdated = this._degreesSpring.update();

            let updated = (xUpdated || yUpdated || scaleUpdated || degreesUpdated);

            if (updated || viewportChanged || !this._fullyLoaded){
                let fullyLoadedFlag = this._updateLevelsForViewport();
                this._setFullyLoaded(fullyLoadedFlag);
            }


            if (updated) {
                this._updateForScale();
                this._raiseBoundsChange();
                this._needsDraw = true;
                return true;
            }
        }

        return false;
    },
```
Should I make a PR or do you want to edit your PR, @pearcetm ?

**Comment by pearcetm** [comment] 2024-02-01 13:54
I modified my PR. I ended up handling it in a slightly different location which I think works better.

**Comment by iangilman** [comment] 2024-02-01 17:27
@jetic83 Thank you for testing out the new build and finding this issue right away! @pearcetm thank you for hopping on it :)

**Comment by pearcetm** [comment] 2024-02-07 02:30
Now that https://github.com/openseadragon/openseadragon/pull/2462 is merged I think this can be closed.

**Comment by iangilman** [comment] 2024-02-07 17:29
Good point!

**Closed by iangilman** 2024-02-07 17:29 UTC
Labels: bug
