### ISSUE TITLE
Broken images at high zoom and multiimages

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#1125] opened 2017-02-06 22:40 UTC
When loading two equally sized images into OSD (overlayed, with addTiledImage()), and then **zooming more then 100%** into the images, the index-0 image shows white rectangular deleted areas, like artifacts which should not be there.

This happens in Chrome 55+ and in Opera 42.

Correct zoom without artifacts are in Firefox 51 and IE 11. However, my fiddle does not work in IE 11 for different reasons I could not figure out now, but I had the problem in IE11 in my application.

[https://jsfiddle.net/3no1xmxu/6/](https://jsfiddle.net/3no1xmxu/6/)

**Comment by iangilman** [comment] 2017-02-08 18:22
I can't reproduce it in your fiddle with Chrome 56 on Mac. I zoomed in as far as I could on the words in the middle. Is there something else I should be doing?

At any rate, one thing to try is using `smoothTileEdgesMinZoom: Infinity` in your viewer options; see if that has an effect.

**Comment by jetic83** [comment] 2017-02-08 18:59
Thank you! Maybe it is only on Windows, which I used. Chrome 56 had the same error with me.

And, yes, `smoothTileEdgesMinZoom: Infinity` solves this issue completely. Now it is working in all browsers.

Solved - Excellent!

**Comment by iangilman** [comment] 2017-02-09 17:20
Great; that should be a fine workaround for you, and also it narrows it down for anyone who wants to dig in and fix the issue.

We already automatically disable smoothTileEdgesMinZoom on iOS because of issues there; I suppose we could do the same for Chrome and Opera on Windows. It'd be nice to know a little bit more about what's causing it, though.

**Comment by LarissaSmith** [comment] 2017-04-26 22:11
I think I may have stumbled on this or a similar issue. I couldn't reproduce the issue on most devices, but a Windows device was showing issues in Firefox, and it appears to be connected to the device pixel density ratio. I used a collection of tiled images and all of them showed the problem. At some canvas widths, at the max zoom level, I saw bars of empty space at the bottom and right edges of the canvas. It was related to the if statement in drawTiles that checks imageZoom against tiledImage.smoothTileEdgesMinZoom being true, and it looked like the scale calculated by tile.getScaleForEdgeSmoothing() was wrong, so the image that it drew didn't fill the canvas. I was testing with a device pixel density of .8, () and it calculated a scale of 1.1363636194304. If I changed the scale to 1, then it drew the image at the right size, so I'm wondering if it just doesn't handle device pixel ratios that are below 1, and if a simple Math.max on the pixel density ratio or the scale calculation would fix it.

It looks like setting smoothTileEdgesMinZoom: Infinity will work to fix this for me as well, but I would rather not disable the setting if it is helpful for some users.

**Comment by avandecreme** [comment] 2017-04-27 11:40
Does this happen with the master branch as well?

**Comment by LarissaSmith** [comment] 2017-05-03 18:04
Yes, I still saw the issue after pulling in the latest changes from the master branch.

**Comment by iangilman** [comment] 2017-05-04 16:54
Interesting... I didn't know there were any devices with pixel density less than 1. @jetic83 is that the same for yours?

@LarissaSmith I'd be down with clamping the pixel density to 1 on the low end, if it fixes the issue. Are you up for making a patch?

**Comment by LarissaSmith** [comment] 2017-05-17 20:49
Sure, I'll give it a try.

**Comment by iangilman** [comment] 2017-05-18 17:48
@LarissaSmith Awesome, thank you :)

**Comment by LarissaSmith** [comment] 2017-05-18 21:21
My testing indicated that clamping the device pixel density to a minimum of 1 did fix the issue, so I've added the PR: https://github.com/openseadragon/openseadragon/pull/1200.

**Comment by iangilman** [comment] 2017-05-19 17:03
Fixed by #1200.

**Closed by iangilman** 2017-05-19 17:03 UTC
Labels: bug
