### ISSUE TITLE
After browser zooming canvas takes up the entire screen and not able to zoom out

### ISSUE THREAD

**Issue by Ganesh1991** [openseadragon/openseadragon#1534] opened 2018-09-07 12:28 UTC
On an iPad pro or other iPad devices, if the user pinch-zooms the browser and an open the image (canvas generated using openseadragon). Not able to zoom out (restore back up to default resolution).

Above Issue is reproducible on the following URL:  Steps for reproduction 
1) Open below https://openseadragon.github.io/ on ipad pro
2) pinch-zooms the browser
3) Navigate to the image container
4) Now try zoom out i.e restore back up to default resolution.

**Comment by iangilman** [comment] 2018-09-10 16:47
Wow, that's a pretty wild one! 

Just to be clear, what's happening here is you zoom the browser outside of OSD and then you zoom the OSD that's on the page. Once you've gotten in that state, even refreshing the browser doesn't fix it. 

I wonder how much control we even have over the browser zoom from the JavaScript?

I suppose one solution would be to stop eating the pinch gesture when we're all the way zoomed out, so the pinch gets through to the browser and zooms it out.

@Ganesh1991 would you be interested in doing some debugging on this?

**Comment by saurabh14t** [comment] 2018-09-17 08:28
Hi @iangilman, 
I am working with him on the above issue. 

Yes we are interested in doing debugging.

**Comment by iangilman** [comment] 2018-09-17 16:11
Wonderful! Let me know what info you might need from me! 

If you try my suggestion (not eating the pinch gesture when all the way zoomed out), that'll be about being able to control the `cancelEvent` calls in https://github.com/openseadragon/openseadragon/blob/master/src/mousetracker.js.

**Comment by iangilman** [comment] 2018-09-17 16:16
See https://github.com/openseadragon/openseadragon/pull/1537 for some ideas...

**Comment by iangilman** [comment] 2018-09-17 16:17
BTW, I've shared that branch so you can see what I'm thinking, but I don't expect I'll be able to continue to work on it right away. Anything you can do is appreciated!

**Comment by Ganesh1991** [comment] 2018-09-18 14:17
Thanks, @iangilman.

**Comment by saurabh14t** [comment] 2019-09-05 09:15
@msalsbery and @iangilman 
Did you get any chance to look into it as this issue is still occuring?

**Comment by iangilman** [comment] 2019-09-05 21:04
I haven't done anything on this. I was expecting you to look into it. I see @msalsbery has assigned it to himself... Hopefully, he'll let us know if he's still planning on working on it!

**Comment by saurabh14t** [comment] 2019-09-06 05:01
I tried your suggestion. However was not able to resolve it.
I forgot about the issue as was busy with other issues.  :)
Hope @msalsbery  will look into it.

**Comment by iangilman** [comment] 2019-09-06 18:47
Can you tell me how my suggestion didn't work? Perhaps there's some way to refine it.

**Comment by msalsbery** [comment] 2019-09-07 01:01
@saurabh14t  The problem is when zooming page in browser large enough so only the OSD viewer is touchable? 

If so, it’s not an easy fix. We would have to know in advance when to let or not let touch events bubble to the page. The side effects of changing our event handling makes fixing stuff like this quite a task.

I am working on making our pointer event class MouseTracker easier to control event bubbling, and with that the browser default handling of events. It’s taking an incredibly long time just working through side effects and trade-offs across multiple browsers and platforms. I will look at this and hopefully there will be a reasonably easy solution that doesn’t affect other stuff negatively. In the meantime, I highly recommend designing pages so a user doesn’t have to zoom pages so much that a viewer window fills the device window...for example, it’s a much nicer experience to provide a resizable viewer element or use the viewer fullscreen/fullpage feature...

If every browser had gesture events standardized, life would be so much easier...

**Comment by saurabh14t** [comment] 2019-09-09 07:04
@iangilman ,
I tried to disable "cancelEvent" when touch event is called and check. 
However when image is zoomed to a level that it cover full screen. It is not allowing to zoom-in back again and it freezes.

**Comment by iangilman** [comment] 2019-09-09 17:24
I see. Well, I think I'm in agreement with @msalsbery: It would be better if your page disabled the browser's page zooming  (like mobile sites typically do), and you handled sizing the page on mobile in more of the standard "responsive" way.

That said, if you want to keep debugging this, you might try using `mouseNavEnabled: false` when you create the viewer as a test... I think that should disable all of OSD's mouse handling, and you can see if the page zooms properly then. Of course, OSD won't zoom at all, but it's just a test.

**Comment by saurabh14t** [comment] 2019-09-10 12:53
@iangilman 
Thanks for the info. 
I tested using "mouseNavEnabled: false" and zoom was working after that. 
I detected the device/OS and updated mouseNavEnabled property depending on device. For the time being issue seems to be working. Though I will test it more.

If @msalsbery  make change  class MouseTracker  please do let me know. 

I will test it further and let you know if I found any issue. 

Thanks for your help.

**Comment by iangilman** [comment] 2019-09-10 20:22
Okay, sounds good... Glad you got something working!

**Comment by saurabh14t** [comment] 2019-09-24 11:14
Hello @iangilman,
I have a query. After updating the property 'mouseNavEnabled ' the scrolling (vertical and horizontal) is disabled after I zoom in inside the container (we have a button to click and zoom as well.
Is there a way to enable the scrolling after 'mouseNavEnabled' is set to false?

**Comment by iangilman** [comment] 2019-09-24 22:22
Do you mean panning around the OpenSeadragon viewer by dragging in it? If so, then no, there's no way to do that when mouse nav is disabled, since panning is part of mouse nav. I mean, I suppose you could catch the events yourself and then implement your own panning if you'd like.

**Comment by saurabh14t** [comment] 2019-09-25 04:27
Ok thanks @iangilman 
I will try to implement it and let you know about it.

**Comment by iangilman** [comment] 2019-09-25 18:38
I still think that setting your page to not zoom on mobile is the best choice. Allowing the browser to zoom the page and also having OpenSeadragon zooming the viewer is likely to cause all sorts of problems (as you've discovered). If you set the page not to zoom, then you should be able to enable mouse nav again get panning for free.

**Comment by iangilman** [comment] 2019-09-25 18:46
Here's another thought... What if you detect how zoomed out the OSD viewer is and disable the mouse nav when you're zoomed all the way out? Maybe that way you can have mouse nav for panning when you're zoomed in, but if you're zoomed out it allows the browser to take the mouse events. You would use `viewer.setMouseNavEnabled(false)` to turn off mouse nav.

**Comment by saurabh14t** [comment] 2019-09-26 06:25
Thanks for the suggestion Ian. :)
I will try to set the page to not zoom on mobile (as first option).
Will let you know about it.

**Comment by saurabh14t** [comment] 2019-10-04 09:01
I tried the first suggestion. However to set page not zoom in IOS is not working. There is a law which restrict it from doing it. 
I tried to implement the 2nd suggestion however it also doesn't work. Could you please suggest how to find if it has zoomed out all the way out inside a container. (It works outside the container area but inside it is not working.)

**Comment by iangilman** [comment] 2019-10-04 17:23
You want to know how to tell if the OSD viewer is zoomed all the way out? You can use `getHomeZoom`, like so:

```
var zoomedOut = viewer.viewport.getZoom() <= viewer.viewport.getHomeZoom();
```

And yes, I had forgotten that iOS doesn't allow you to restrict zooming anymore. Still, if you default to already zoomed in on the page, like so:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
```

...The user is less likely to want to zoom in.

**Comment by saurabh14t** [comment] 2019-10-07 04:51
Thanks for it Ian.
We have already implemented meta tag in our code. However zooming is required in our code to certain level so we were trying the above approach. 

I will try the 1st approach you gave and will let you know about it.

**Comment by saurabh14t** [comment] 2019-10-14 05:07
Hi @iangilman ,
We got up with another issue while resolving above issue.
On new IOS version 13 when I click on the image for the first time it is not zooming (pinchToZoom is enabled). However when I click outside the container and zoom in and zoom out and then again zoom on the image the zoom is working fine, It is working on IOS version 12. 
I tried to find out if there was any change on the zooming functionality for IOS 13. but was not able to find any.
Could you please suggest and let me know what could be the issue.

**Comment by iangilman** [comment] 2019-10-14 17:46
Can you help me understand how to reproduce this new issue? Are you saying that you're expecting a single tap on your viewer to result in zooming in? I don't think single tap to zoom is standard behavior; have you turned it on explicitly? It's not affected by `pinchToZoom` (which only affects pinches, not taps).

I have a device on iOS 13. I took it here:

http://openseadragon.github.io/

* Single tapping on the viewer does nothing, as expected.
* Pinching to zoom on the viewer works immediately, as expected.
* Double tapping on the viewer zooms in, as expected.

Let me know how that's different from what you're experiencing.

**Comment by saurabh14t** [comment] 2019-10-15 01:03
Sorry for the confusion Ian. I am pinching on viewer to zoom and 1st time it is not zooming. And when I pinch outside the viewer it zooms in and when I pinch zoom again on viewer it  works as expected. 
I checked on above site and it is working as expected. Not sure why it is happening on our site.

**Comment by saurabh14t** [comment] 2019-10-15 07:11
Sorry for the confusion Ian. 
The issue is when mouseNavEnabled is false and pinchtozoom is false.
I am pinching on viewer to zoom and 1st time it is not zooming. And when I pinch outside the viewer it zooms in and when I pinch zoom again on viewer it works as expected.
I checked on your site and it is working as expected. Not sure why it is happening on our site.

**Comment by iangilman** [comment] 2019-10-15 21:13
Interesting! When you say pinchToZoom is false, I assume you mean true?

If you make mouseNavEnabled true on your site, do you have the same issue?

**Comment by saurabh14t** [comment] 2019-10-16 00:58
For gesturesettingtouch I have set pinchToZoom to false. 
Yes even if I make mouseNavEnabled to true it has same issue. 
Also if I set pinchToZoom to true for gesturesettingtouch and I zoom inside the viewer it zooms inside it only but if I zoom outside the viewer and then zoom inside the viewer it zooms whole page not only viewer.
I think browser zoom is taking precedence once I zoom outside the container/viewer.

**Comment by iangilman** [comment] 2019-10-16 21:37
Strange... It should not be zooming the viewer at all when you pinch if you have `pinchToZoom` set to false.

I guess your best bet is to figure out what you're doing different from http://openseadragon.github.io/ so we can isolate what's causing the issue. If you can provide a simplified repro page, that would be helpful.

**Comment by saurabh14t** [comment] 2019-11-06 05:06
Hi @iangilman,
Sorry for late reply. 
I will figure out the difference and let you know about it.

**Comment by saurabh14t** [comment] 2019-11-14 09:34
Hi @iangilman, 
Sorry for delayed response. Repro page is not possible as cannot share the code due to policy.

In our code the page is divided into 3 parts. 1st is header, 2nd is container(where openseadragon-container is set up) and 3rd is footer. 
 The openseadragon-container (2nd part ) is not in full screen. It has some height set up and it is inside that area. so if we click outside the openseadragon-container the browser zoom is taking precedence. 
I have attached the screenshot it would help you to get the idea what might be happening.

![image](https://user-images.githubusercontent.com/31381096/68844583-0b510c00-06f0-11ea-887c-234958651b1c.png)


Is there a way we can manually trigger the browser zoom when we touch in the device?

**Comment by iangilman** [comment] 2019-11-14 21:45
Thank you for the explanation. Looks like it's an overlay that pops up over other content; good to know.

I don't know of any way to manually trigger browser zoom, but that's certainly something you could look up independently of OpenSeadragon. 

I understand that you're not allowed to share your project's code externally, but a simplified repro would be a fresh piece of code that just demonstrates the issue as simply as possible, without any of your proprietary information. Part of the value of creating such a thing (besides being to share with people who could help) is that the process can help you understand the dynamics. Anyway, I understand if you can't do even that, but I'm running out of ideas for how to help you otherwise.

**Comment by saurabh14t** [comment] 2019-11-15 11:13
sure @iangilman. 
I will create a repro page and will share the link.

**Comment by saurabh14t** [comment] 2019-11-18 07:40
Hi @iangilman ,
Please find below the repro page. https://demo.figmd.com/Certlink/openseadragon/testopenseadragon.html.
 
In this I have updated mouseNavEnabled:false, 
When you open the page on safari browser in IOS12 the image is getting zoomed when clicking above it and outside it. And when you open it in IOS13 the image is not getting zoomed when clocking above it and when clicking outside it is getting zoomed. 

Please have a look into it.

**Comment by iangilman** [comment] 2019-11-18 23:36
Fantastic! This helps a lot. It looks like we're setting `touch-action: none` on the CSS for `viewer.canvas` and this is stopping the default browser zooming behavior. It looks like iOS 12 was ignoring that and allowing you to zoom anyway, and iOS 13 has fixed that bug and now properly obeys the `touch-action` directive.

Here's where we're setting it:

https://github.com/openseadragon/openseadragon/blob/68e9efebe699c5c47f274b572a9409d267bafaa7/src/viewer.js#L254

Probably we should unset it whenever mouseNav is turned off, so the default browser behavior can happen.

Would that be enough to fix your issue? It would make iOS 13 act like iOS 12 does.

BTW, the `touch-action` bit was added in https://github.com/openseadragon/openseadragon/pull/448, looks like to fix various touch issues. Do you remember what it's for, @msalsbery? 

Note that you can potentially use `touch-action` to stop the standard browser zoom (at least on iOS 13) if you want to.

**Comment by saurabh14t** [comment] 2019-11-19 09:25
@iangilman 
Thanks for the help. :+1: 
I changed the setting when mousenavenabled is false and it is working. 

I will test it (also assign it for testing) and will let you know if in case of any issue.  (Unless something else creeps up )

Thanks for your explanation of the issue. You helped a lot on getting it fixed.

**Comment by iangilman** [comment] 2019-11-19 19:52
Fantastic! Glad to hear it :)

**Comment by msalsbery** [comment] 2021-03-09 19:50
@saurabh14t 

#1872 has landed! Are you still having issues here or did you get it sorted?

**Comment by saurabh14t** [comment] 2021-03-10 13:29
@msalsbery 
I got it sorted with the suggestion of @iangilman .
Thanks for checking it.

**Closed** 2021-03-10 13:47 UTC
Labels: bug
