### ISSUE TITLE
When loading some IIIF tilesets, incorrect URL's are being fetched for certain tiles

### ISSUE THREAD

**Issue by callan-datarock** [openseadragon/openseadragon#2321] opened 2023-03-22 03:40 UTC
I'm trying to build an OSD canvas that takes images from multiple groups of IIIF tilesets, each with their own `info.json` and source images. These are then stacked, one on top of each other, sequentially down the canvas. This has been implemented fine and can create a canvas that works great for the most part.

When trying to use an IIIF source to load some of these "rows" into OSD, there are occasional errors with OSD fetching tiles that include the wrong URL. This doesn't happen with every single group of IIIF tilesets, but for the ones where it does happen, it is a consistent reproducible error.

Examples:
URL that OSD generates to get a particular tile: 
`my-server.com/my-images/image_001/8192,0,1836,604/57,/0/default.jpg` 

info.json:
```
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "https://my-server.com/my-images/image_001",
  "profile": [
    "http://iiif.io/api/image/2/level0.json",
    {
      "formats": [
        "jpg"
      ],
      "qualities": [
        "default"
      ]
    }
  ],
  "protocol": "http://iiif.io/api/image",
  "tiles": [
    {
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32
      ],
      "width": 256
    }
  ],
  "width": 10028,
  "height": 604
}

```
URL:
`my-server.com/my-images/image_002/8192,0,1765,601/55,/0/default.jpg`

info.json:
```
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "https://my-server.com/my-images/image_002",
  "profile": [
    "http://iiif.io/api/image/2/level0.json",
    {
      "formats": [
        "jpg"
      ],
      "qualities": [
        "default"
      ]
    }
  ],
  "protocol": "http://iiif.io/api/image",
  "tiles": [
    {
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32
      ],
      "width": 256
    }
  ],
  "width": 9957,
  "height": 601
}
```

The _actual_ location of the image on the server:
`my-server.com/my-images/image_001/8192,0,1836,604/58,/0/default.jpg`
`my-server.com/my-images/image_002/8192,0,1765,601/56,/0/default.jpg`
...

Patterns that I've recognized are
- it's _always_ happening with tiles that are scaled from the right hand side of the root image - I.E there are never bad fetches from the start or middle of an IIIF tileset
- it's _always_ OSD that queries the `size.w` param as one less than what's actually provided by the server - E.G `.../8192,0,1836,604/57,/...`, instead of `.../8192,0,1836,604/58,/...`

These tiles that fail to load tend to only become visually apparent when zoomed out in the OSD canvas - for some reason, when zooming in, OSD can generate the URL's for the higher resolution tiles just fine. Im not sure if this is consistent, but for all the example images I'm using in my project, this has been the case.

You'll notice that the height and width properties for each source image are different between the two groups - each group that I'm trying to build has a slightly different dimensions, but naively I would assume that as long as OSD adheres to the IIIF spec, it shouldn't matter.

Considerations: 
- I have tried using two different libraries to generate these IIIF tilesets (https://github.com/lovell/sharp + https://github.com/glenrobson/iiif-tiler), and both of these create identical IIIF tilesets - I do not believe the source image mapping is the problem, but rather OSD since that's the common denominator. 
- I have generated tilesets with multiple `size` parameters (128, 256, 512, 1024) - while the generated tilesets will be different, there will still typically be a few of these issues when OSD tries to load any of them, and it will still always be the end tiles.

I have a gut feeling that this seems to be some sort of `Math.round()` error, since the problematic tiles are always off by 1. Perhaps the IIIF implementation in OSD is handling odd numbers weirdly when generating the URL from the size/scale factor params in the `info.json`? If that's the case, it would be good to try and fix it - would like to try and plug all these holes in my OSD canvas 😄

**Comment by callan-datarock** [comment] 2023-03-24 03:42
Update: seems that this problem doesn't exist in version 3.1, but does exist in version 4.0.

**Comment by filak** [comment] 2023-03-24 17:25
Sorry to hear that. Do you have any minimal skeleton app so I can test this issue?

Are the problematic tiles missing or just distorted?

Would you mind sharing a screenshot?

**Comment by iangilman** [comment] 2023-03-31 23:15
Strange. #2206 changed from `ceil` to `round` so it does seem that it may be the cause of this. Of course, the reason for that PR was that we were getting bad numbers in the other direction sometimes. I guess there must be some nuance we're missing? 

@callan-datarock Thank you for the thorough write-up! Can you work with @filak to get to the bottom of this? 

@azaroth42 Any thoughts from a IIIF perspective?

**Comment by iangilman** [comment] 2023-03-31 23:21
FWIW, when I asked in the IIIF's Slack about #2206 originally, there was this comment: 

<img width="806" alt="image" src="https://user-images.githubusercontent.com/338989/229249073-4b2f2d66-bb76-43c2-b71c-2b5c28392af0.png">

I'm going to mention this new issue there and see if anyone has anything to say.

**Comment by ahankinson** [comment] 2023-04-03 12:10
The IIIF Tiler by Glen Robson uses `ceil` for the number of layers: https://github.com/glenrobson/iiif-tiler/blob/main/src/main/java/uk/co/gdmrdigital/iiif/image/ImageInfo.java#L136

I suspect that some, but not all, of the places where `round` has been used should actually be `ceil`. So it would be good if @callan-datarock could try going through and replacing `round` with `ceil` one-by-one to see if it fixes it, and then if @filak could verify that this does not cause problems with his.

**Comment by pearcetm** [comment] 2023-04-03 13:26
In the [issue](https://github.com/openseadragon/openseadragon/issues/2198) related to the PR by @filak that changed `ceil` to `round`, @ruven noted the following: 
> [ruven](https://github.com/ruven) commented [on Sep 13, 2022](https://github.com/openseadragon/openseadragon/issues/2198#issuecomment-1245420721)
> > Also, what about round instead?

> The IIPImage server [uses round() internally](https://github.com/ruven/iipsrv/blob/ffe319016e6b7de57778083a033b7b320e3a9247/src/IIIF.cc#L448) to calculate these sizes for IIIF.https://github.com/openseadragon/openseadragon/issues/2198#issuecomment-1245420721

But as @ahankinson notes

> The IIIF Tiler by Glen Robson uses `ceil` for the number of layers: https://github.com/glenrobson/iiif-tiler/blob/main/src/main/java/uk/co/gdmrdigital/iiif/image/ImageInfo.java#L136

The math behind both @filak's issue as well as @callan-datarock's looks essentially the same to me. Could there be a discrepancy in how IIPImage server versus the tiler utilities are handling the calculation on the back end?

**Comment by ahankinson** [comment] 2023-04-03 16:30
There are different calculations happening. I think for max layers the calculation should probably use `ceil`, but I’m not sure about the calculations for the image sizes?

**Comment by pearcetm** [comment] 2023-04-04 14:39
@filak Could you try using one of the converters that @callan-datarock mentioned (https://github.com/lovell/sharp or https://github.com/glenrobson/iiif-tiler) to convert the same file you're having issues with when you use `IIPImage server`? Based on your example and the behavior that @callan-datarock has described, it seems that the server wants widths rounded to the nearest whole number, but the converters might use `ceil` to always round up. Trying your file with both methods might shed some light.

**Comment by pearcetm** [comment] 2023-04-04 22:53
I had a chance to look into `iiif-tiler`. Here's the code for [generating the tiles and URLs ](https://github.com/glenrobson/iiif-tiler/blob/3198e8371ea967d7e0893263ae9a52d1e6e68267/src/main/java/uk/co/gdmrdigital/iiif/image/Tiler.java#L108-L125)when tiling an image.  As you can see, `Math.ceil` is used - thus, always rounding the final column/row up, rather than to the nearest integer value.
```
  for (int x = 0; x < tTileNumWidth; x++) {
      for (int y = 0; y < tTileNumHeight; y++) {
          int tileX = x * _image.getTileWidth() * scale;
          int tileY = y * _image.getTileHeight() * scale;
          int scaledTileWidth = _image.getTileWidth() * scale;
          int tiledWidthCalc = _image.getTileWidth();
          if (tileX + scaledTileWidth > _image.getWidth()) {
              scaledTileWidth = _image.getWidth() - tileX;
              tiledWidthCalc = (int)Math.ceil((double)scaledTileWidth / scale);
          }
          int scaledTileHeight = _image.getTileHeight() * scale;
          int tiledHeightCalc = _image.getTileHeight();
          if (tileY + scaledTileHeight > _image.getHeight()) {
              scaledTileHeight = _image.getHeight() - tileY;
              tiledHeightCalc = (int)Math.ceil((double)scaledTileHeight / scale);
          }


          String url = "./" + tileX + "," + tileY + "," + scaledTileWidth + "," + scaledTileHeight + "/" + tiledWidthCalc + ",/0/default.jpg";
```

So - I think what this issue and @filak's prior issue ([https://github.com/openseadragon/openseadragon/issues/2198](url)) boil down to, is that a lot of existing pre-tiled IIIF images worked for a long time with the code that used `ceil`. https://github.com/openseadragon/openseadragon/pull/2206 changed this to `round`, which may be (is?) more technically correct and works correctly with https://github.com/ruven/iipsrv, but breaks a subset of existing pre-tiled images.

How to resolve this while preserving compatibility with   

  1) existing resources depending on `ceil`
  2) live servers expecting `round` 

is an open question.

**Comment by iangilman** [comment] 2023-04-04 22:57
Thank you all for the great sleuthing! 

If it's a matter of different IIIF generators doing different things, do we need to add some sort of compatibility flag, so you can specify which tiler you're using?

Should we reach out to the various generators/servers and see what they have to say?

**Comment by ahankinson** [comment] 2023-04-05 07:22
Maybe @glenrobson can advise on the best way to proceed; perhaps this is something that can be clarified in the IIIF specification, or at least as a technical note on the website?

**Comment by glenrobson** [comment] 2023-04-05 10:39
Its a good question, it looks like I switched to Math.ceil in this [pull-request](https://github.com/glenrobson/iiif-tiler/commit/ab4db41790ffd9b9588e96477aa695470ca098d0#diff-1393d8ab37ca27c4e7031efdefac81b77f480938b48fe7d3ba7da489e859ea7b) but I suspect I was doing it to match with the OSD behaviour at the time. 

The only guidance I can find now on this, is this [implementation note](https://iiif.io/api/image/3.0/implementation/#3-tile-region-parameter-calculation) which seems to say use `floor()` for integer division but also says "Note that the rounding method is implementation dependent." 

Ill ask the IIIF editors if they can provide some guidance.

**Comment by glenrobson** [comment] 2023-04-05 11:33
There was also this discussion in 2014 which seemed to lean to `ceil`: https://github.com/IIIF/api/pull/250

**Comment by ruven** [comment] 2023-04-06 08:53
I'll have a closer look at this. It would be interesting to check what each IIIF server is  in fact doing in practice. Rounding to nearest seems intuitively to me the most logical way to round, but if everyone else is rounding up, then I'll change the IIPImage implementation to match.

The problem is that the IIIF specification doesn't specify how things should be rounded. The only mention of rounding is in the implementation notes, where it only says that [the rounding method is implementation specific](https://iiif.io/api/image/3.0/implementation/#3-tile-region-parameter-calculation).

The thing to bear in mind, though, is that there are two kinds of rounding taking place. There's the rounding that occurs when a viewer calculates the dimensions to request, which is the issue here with OSD. But there are also the sizes of the resolutions that exist physically within the image file itself. Different software (Kakadu, vips, imagemagick etc) don't necessarily round the resolution levels in the same way. In theory, this shouldn't be an issue, as the iiif.info file has the [`sizes`](https://iiif.io/api/image/3.0/#53-sizes) variable, which can allow the server to let the viewer know exactly what resolution sizes exist. The info.json at the top of this thread, however, doesn't supply this information, which doesn't allow OSD to take this variability into account.

**Comment by azaroth42** [comment] 2023-04-06 11:58
> Different software (Kakadu, vips, imagemagick etc) don't necessarily round the resolution levels in the same way.

If I recall correctly, and it was a long time ago now so I might not, it was this reason that led us to conclude that we couldn't reasonably require a specific rounding method. 

That said ... it was a long time ago now and we should reconsider whether the spec needs to specify the rounding method as a MUST to avoid this situation.

**Comment by iangilman** [comment] 2023-04-11 21:35
Thank you all for chiming in here! Looks like we've been covered a bit of a mess. 

We're hoping to release version 4.0.1 of OSD soon, and that will be the last version before some major changes, which will become 5.0.0. I'd love to get this sorted out for this upcoming version, if possible. 

@callan-datarock Can you confirm whether the code reversion @filak [is proposing](https://github.com/openseadragon/openseadragon/issues/2321#issuecomment-1497419470) fixes the issue you're having? If not, would you be able to isolate which of the changes in #2206 is causing the problem that's affecting you? 

In this way, we may be able to find a balance that works for everyone. If not, we may need to add a flag that people can set depending on which IIIF source they are using.

**Comment by glenrobson** [comment] 2023-04-13 00:44
I've been doing some testing with awkward sized images to see if there is a strong reason to go for `ceil` or `round` and I would like to propose a switch back to the original `ceil` that was in replace by `round` in https://github.com/openseadragon/openseadragon/pull/2206. 

The first reason is that I think most level 0 image servers will use `ceil` as this was OSD's original behaviour and also is the behaviour of [leaflet](https://github.com/mejackreed/Leaflet-IIIF/blob/6cb256e8d4d2dd508e98eb8a337dfa5407bee5db/leaflet-iiif.js#L56). 

The second reason is due to an edge case detailed below where `ceil` works correctly but `round` asks for a 0 width image which isn't allowed. (I've been testing a number of images to try and see what affect ceil and round have).

The example image is [here](https://glenrobson.github.io/iiif_stuff/rounding_issue/odd.jpg) and it has a width and height of 3073 which make it awkward as it doesn't divide into tiles nicely, as at most zoom levels it has a pixel left over. I've got OSD v4.0.0 and v3.1.0 setup [here](https://glenrobson.github.io/iiif_stuff/rounding_issue/) connected to a level 0 version of the image for testing. v3.1 finds all of the correct tiles but v4 has the issues described below. 

Looking at the effects the rounding has on the level0 image server generated by iiif-tiler:

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L380-L381

Is used to check whether you should use full/max for size or ask for full width and height as the tile is close to a full sized image. For the zoom levels I have in my code:

 * levelWidth = 3073 * .5 = 1536.5 will be 1537 for round and ceil
 * levelWidth = 3073 * .25 = 768.25 will be 768 for round and 769 for ceil only 769 exists for my image.
 * levelWidth = 3073 * .125 = 384.125 will be 384 with round and 385 for ceil. I have 385
 * levelWidth = 3073 * 00625 = 192.0625  will be 192 with round and 193 with ceil I have 193 which causes this request to fail:
[/odd/full/192,/0/default.jpg ](https://glenrobson.github.io/iiif_stuff/rounding_issue/odd/full/192,/0/default.jpg) - I have [/odd/full/193,/0/default.jpg](https://github.com/glenrobson/iiif_stuff/tree/master/rounding_issue/odd/full/193%2C/0).

So this fails due to the different between ceil and round but could be fixed if we agreed on one.  

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L401-L402

This should almost always return an int anyway unless tileWidth/tileheight not devisable by a power of 2. Although I believe OSD uses decimal fractions for scale so tileWidth should be devisable by 0.5 0.25 0.125 etc (1/2 1/4 1/8). iiif-tiler and I believe most other IIIF image servers work with powers of 2 so this shouldn't be an issue. 

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L429-L430

This change causes the following requests to fail:

https://glenrobson.github.io/iiif_stuff/rounding_issue/odd/2048,0,1025,2048/128,/0/default.jpg - top right
https://glenrobson.github.io/iiif_stuff/rounding_issue/odd/2048,2048,1025,1025/128,/0/default.jpg - bottom right 

This is for zoom level 1/8 (scale 0.125) and the tileWidth is 1025 which produces:
```
iiifSizeW = Math.round( iiifTileW * scale );
1025 * 0.125 = 128.125 
Math.round(128.125) is 128 
Math.ceil(128.125) is 129 
```

So again this is one off the image I have and could be fixed by agreeing to round or ceil. It also fails to find the following images:

https://glenrobson.github.io/iiif_stuff/rounding_issue/odd/3072,1024,1,1024/0,/0/default.jpg - bottom right
https://glenrobson.github.io/iiif_stuff/rounding_issue/odd/3072,2048,1,1024/0,/0/default.jpg- bottom right

https://glenrobson.github.io/iiif_stuff/rounding_issue/odd/3072,0,1,1024/0,/0/default.jpg - right top 
https://glenrobson.github.io/iiif_stuff/rounding_issue/odd/3072,3072,1,1/0,/0/default.jpg - right top

Which are the 1 pixel remainders for zoom level 4 (scale 0.25):

At scale 0.25 ideally OSD wants tiles of 1024 and 1024 but this only has 1 pixel so tileWidth is 1:
```
iiifTileW = 1 
Scale = 0.25

iiifSizeW = Math.round( iiifTileW * scale );
iiifSizeW = 0.25 * 1 = 0.25 

Math.round(0.25) = 0
Math.ceil(0.25) = 1
```
Using round on 0.25 we get a width of 0 but using ceil we get a width of 1. So using ceil generates:

https://glenrobson.github.io/iiif_stuff/rounding_issue/odd/3072,1024,1,1024/1,/0/default.jpg

which is correct in this case. 

So this is a very edgy edge case but I think it suggests that `ceil` might be a better option in the short term as it replicates previous behaviour and works better for some awkward use cases. It would be good to formalise this in the IIIF specification so that all image servers handle this in the same way.

**Comment by ruven** [comment] 2023-04-13 21:21
Going back to @filak's original issue https://github.com/openseadragon/openseadragon/issues/2198, the core of the problem was that OSD was only setting a width for the IIIF request and not the height. This forced the server to itself calculate the height, which resulted in a value not matching what OSD was expecting. Perhaps a robust solution here would be for OSD to always specify both width and height, then the IIIF server will always give you exactly what you ask for regardless of rounding. Is there in fact a reason why OSD only sets the width?

Regarding server-side rounding, I'm happy to switch IIPImage to ceil for IIIF size calculations. Rounding only occurs in 2 situations: when only one of the width or height dimensions is given and secondly, when you specify sizes as percentages.

But although standardizing all IIIF implementations would improve things, it's not a full solution for OSD as there are still  the physical dimensions of each resolution that exist within the image file itself. These resolutions exist independently of the IIIF server and can be rounded up or down according to the software you used to create the image. All level>1 IIIF servers provide a list of "sizes" in the info.json file (at least IIPImage and Canteloupe do). These give you the existing resolution sizes, but these don't seem to be used by OSD. The code here, for example: https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L380-L381 just scales things rather than use the provided list. It looks to me like the resolution sizes are only used when no tile information has been provided. So, what about using the provided sizes list to get the resolution size instead of calculating it with possibly incorrect rounding?

**Comment by glenrobson** [comment] 2023-04-13 22:25
>  Perhaps a robust solution here would be for OSD to always specify both width and height, then the IIIF server will always give you exactly what you ask for regardless of rounding. Is there in fact a reason why OSD only sets the width?

I'm afraid for IIIF v2 the [Canonical URL](https://iiif.io/api/image/2.1/#canonical-uri-syntax) is to only specify the width if you want to maintain the aspect ratio. For v3 the [Canonical URL](https://iiif.io/api/image/3.0/#48-canonical-uri-syntax) requires both the width and the height and OSD implements this correctly for both versions. If you were to specify a width and height for a v2 level0 image server the tile wouldn't exist. 

> Would you say we should revert all of the round calls from https://github.com/openseadragon/openseadragon/pull/2206, or just some?

The two that cause issues with my level0 image are:

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L380-L381

and 

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L429-L430

The following I think should be OK left as round as is it will mostly result in an int anyway for most implementations:

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L401-L402

For this one I'm not sure as my tiler provides scale factors but as @filak mentions the other one already uses round so I'm not sure of the affect.:

https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L137 

> So, what about using the provided sizes list to get the resolution size instead of calculating it with possibly incorrect rounding?

This using the sizes array would fix one of the issues when requesting the full region. I think you would still have a rounding issue with the edge tiles. 

Note there are a few IIIF image servers that don't provide sizes (to name two: [Smithsonian](https://ids.si.edu/ids/iiif/AAA-jacqself00001/info.json) and [IIIF Fixtures](https://iiif.io/api/image/3.0/example/reference/28473c77da3deebe4375c3a50572d9d3-laocoon/info.json) so we'd also have to have the rounding fallback for those cases.

**Comment by iangilman** [comment] 2023-04-14 01:35
@glenrobson Wow, thank you for the thorough write up! I agree that `ceil` makes sense. Would you say we should revert all of the `round` calls from  #2206, or just some? 

@filak What would you think about this? Should we provide some sort of flag to enable your use case?

**Comment by ruven** [comment] 2023-04-14 09:11
> This using the sizes array would fix one of the issues when requesting the full region. I think you would still have a rounding issue with the edge tiles.

Not really, because the calculation for the edge tile can be done without rounding. The calculation just becomes image size at this level - starting position of this tile. So for the calculation here: https://github.com/openseadragon/openseadragon/blob/60a6a610e04983a3ebcdb4273c8b8edca188fb33/src/iiiftilesource.js#L429-L430
you would add something like this to take the real size into account at the edges:
```
if ( iiifTileW < iiifTileSizeWidth ) {
  iiifSizeW = levelWidth - iiifTileX;
}
```

> Note there are a few IIIF image servers that don't provide sizes (to name two: Smithsonian and IIIF Fixtures so we'd also have to have the rounding fallback for those cases.

Sure, if sizes isn't provided, fallback to how it is now. But if it is provided, it's a shame not to use that information.

**Comment by filak** [comment] 2023-04-14 12:17
Based on the discussion I would suggest to

1. avoid ceil/round whenever possible - ie. compute the other size if possible
2. use ceil in cases where there is the risk of rounding a value to 0
3. agree to make ceil the default/fallback method where applicable - which might need to be fixed/implemented in some image servers/tile source generators

Maybe the default/fallback method shall be configurable via OSD to fit different backends ?

**Comment by ahankinson** [comment] 2023-04-14 12:30
> Maybe the default/fallback method shall be configurable via OSD to fit different backends ?

A single OSD instance is often used to talk to multiple backends, since it is a component of almost every IIIF viewer. This means a fixed configuration for a backend would not work.

**Comment by filak** [comment] 2023-04-17 11:00
@ahankinson Configurable does not mean fixed right ?

**Comment by ahankinson** [comment] 2023-04-17 12:29
From what I understand of your suggestion, if I'm hosting an OSD instance and want to say "backend: iip" or "backend: static" or something like that, to change the behaviour of round / ceil, then my OSD instance would be configured to expect only tiles from that source, and would break on others.

This would break most IIIF viewers, since they will load images from multiple possible backends on the same instance, depending on the manifest that is loaded. So one IIIF manifest from one institution might use one tile server (e.g., IIP, or digilib) while another manifest might use a different backend (static tiles, canteloupe). The same viewer instance (using the same OSD configuration) would need to be able to work with all of these.

So it is "fixed" in the sense that you would need to set it when you instantiate your OSD instance. This could only happen if you are the developer and control the code and the OSD deployment. You could not change my configuration for my OSD instance if you did not have access to my server. 

So it's probably a bad idea to hardcode any list of behaviours for specific backends in OSD.

**Comment by ruven** [comment] 2023-04-17 21:46
I've added the ability to use the resolution sizes provided in the info.json "sizes" field to determine exact tile sizes for each level in this pull request https://github.com/openseadragon/openseadragon/pull/2337. If this information exists in the info.json file, OSD can calculate tile sizes without having to round at all. If no information is provided, OSD falls back to using ceil() to calculate. I had to add a new function getLevelSize() to keep things clean and modify getNumTiles() as OSD natively assumes ceil() when calculating this, giving incorrect tile counts.

Requesting correct tile dimensions also has the advantage of having the tiles perfectly aligned with the underlying image file structure, making image requests slightly faster.

I've tested with iiif-tiler, IIPImage and Canteloupe and they all seem to work correctly with no erroneous tiles being requested. But this should be tested more thoroughly.

By the way, I noticed that the [IIIF info.json spec](https://iiif.io/api/image/3.0/#53-sizes) says that the sizes field is for "scaled versions of the full image", which seems to imply that this array doesn't need to include the full resolution size. IIPImage, therefore, only includes the sub-resolutions in the array. However, Canteloupe and iiif-tiler do include the full resolution. Any thoughts anyone on the correct use of "sizes"?

**Comment by iangilman** [comment] 2023-04-18 21:05
@ruven Awesome, thank you for making that PR! 

I would love it if the other folks here would take a moment to look over #2337 and see if there is anything that should be addressed in it before merging!

**Closed** 2023-04-27 21:24 UTC
Labels: bug

**Comment by iangilman** [comment] 2023-04-27 21:30
Okay, hopefully this is sorted out now, with #2337 merged. Thank you all for engaging in the discussion and helping to track it down! I leave it to you to decide whether the IIIF spec needs updating, or whether any IIIF tools and servers need to be brought into alignment.

**Comment by glenrobson** [comment] 2023-04-28 12:03
Thanks Ian and everyone for working on this issue. I've created an issue in the IIIF API repository for the editors to look at any changes that are required to the IIIF Specifications: https://github.com/IIIF/api/issues/2232

**Comment by iangilman** [comment] 2023-04-28 20:54
@glenrobson Awesome, perfect!
