### ISSUE TITLE
viewer.addOverlay() not work fine when image is flipped

### ISSUE THREAD

**Issue by Edo2610** [openseadragon/openseadragon#2304] opened 2023-02-22 07:45 UTC
Adding an overlay to some position not work when flip is toggle, the overlay is added like the image is not flipped.
Once image is fliped and the overlay is added, if image rotate the overlay rotate in the opposite direction.

**Comment by MohitBansal321** [comment] 2023-02-25 14:55
please you provide testing code

**Comment by iangilman** [comment] 2023-02-27 18:47
This is a duplicate of https://github.com/openseadragon/openseadragon/issues/1614

**Closed by iangilman** 2023-02-27 18:47 UTC
Labels: bug
