### ISSUE TITLE
Going full screen when at max zoom causes further zoom

### ISSUE THREAD

**Issue by jstevensonhoare** [openseadragon/openseadragon#459] opened 2014-08-14 10:07 UTC
Set the Viewer.Options.maxZoomPixelRatio to 1 and then zoom until cannot zoom any further on a non-full screen image. Now click the 'Toggle full page' button.

Expected result: Image is shown full screen at the same zoom factor (i.e. no size change).

Actual result: Image is shown zoomed further (i.e. size increases).

Left-clicking in image at now full screen state causes image to return to same size as when non-full screen.

**Comment by avandecreme** [comment] 2015-05-16 15:03
I just had a quick glance at it. Here are some notes for later:
-this is actually not specific to full-screen. Anytime the viewer is resized, the same code is called.
-when trying to reproduce the issue on http://openseadragon.github.io/, sometimes I get the "over zoom" described above, sometimes I am getting almost home.

**Comment by iangilman** [comment] 2015-05-18 16:27
:+1:

**Comment by iangilman** [comment] 2015-06-23 16:21
Fixing this might be as simple as changing `fitBounds` to `fitBoundsWithConstraints` on https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L2942

**Comment by avandecreme** [comment] 2016-05-12 23:34
It turns out that the "preserving zoom level" option is already supported by the `preserveImageSizeOnResize` option: http://openseadragon.github.io/docs/OpenSeadragon.html#Options
I wonder if the default should be `true`.

Also, I can't reproduce this bug in #934, so it is probably fixed.

**Comment by iangilman** [comment] 2016-05-13 16:52
Hmm... thinking about it now I still think preserveImageSizeOnResize = false is a good default... in that way the image acts more like an <img> tag, scaling as it grows. I think this is the behavior of least surprise. Also, of course, there's something to be said for not flipping the defaults of existing options. 

@avandecreme Do you think #934 fixed it, or it was already fixed somewhere else in master? Not that it really matters I suppose... just curious.

**Comment by avandecreme** [comment] 2016-05-13 17:36
> Hmm... thinking about it now I still think preserveImageSizeOnResize = false is a good default... in that way the image acts more like an tag, scaling as it grows. I think this is the behavior of least surprise. Also, of course, there's something to be said for not flipping the defaults of existing options. 

Fine with me.

> @avandecreme Do you think #934 fixed it, or it was already fixed somewhere else in master? Not that it really matters I suppose... just curious.

I don't think #934 fixed it. I should test further with duomo and compare with what we have on http://openseadragon.github.io. It seems that going to fullscreen currently always reset to the home zoom (but keeps the center).

**Comment by iangilman** [comment] 2016-05-17 16:51
Fixed by #940.

**Closed by iangilman** 2016-05-17 16:51 UTC
Labels: bug
