### ISSUE TITLE
Browser crash when scale up to max zoom level on iPadOS13

### ISSUE THREAD

**Issue by sanli** [openseadragon/openseadragon#1728] opened 2019-10-30 05:07 UTC
After upgrade my iPad to iPadOS 13.1.3, browser start to crash when scale up to max zoom level with multi touch.  
Sample URL: [http://ltfc.net/img/5d71ff60038b98321da149b8](http://ltfc.net/img/5d71ff60038b98321da149b8)

It's kinda hard to replicate, need try some times. Some our clients report same issue these days, it seems not just happed on my iPad.
Sample Video: [http://cagapp-static.ltfc.net/1572410136161017.mp4](http://cagapp-static.ltfc.net/1572410136161017.mp4)

Sometimes the browser not crash, I can get some exception on console. it's a JS error of mouse tracker:
![image](https://user-images.githubusercontent.com/330888/67828435-58d55280-fb0e-11e9-8cfb-f0586d195294.png)

ENV: 
iPad: iPadOS13.1.3 , 
OSD:  2.4.1
Browser: Safari / UIWebView

**Comment by iangilman** [comment] 2019-10-30 18:41
Looks like this might be the same as https://github.com/openseadragon/openseadragon/issues/1724. You might want to join the conversation there.

**Comment by deminoth** [comment] 2019-12-13 06:11
Maybe this related with #952. In iPadOS13, Safari's user agent doesn't contain `iPad`. You can try an `iOSDevice` option.
Should we detect `Safari` instead of `iPad`?

**Comment by iangilman** [comment] 2019-12-13 19:35
@deminoth interesting. What is the iPad iOS 13 user agent? We shouldn't just look for `Safari` because that could be the desktop version as well.

**Comment by deminoth** [comment] 2019-12-14 07:21
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15`. Safari uses a 'desktop mode' as default in iPadOS13.

**Comment by iangilman** [comment] 2019-12-16 18:33
Hmm... That doesn't look very helpful. We would need to figure out how to spot the iPad specifically (assuming that this problem we're trying to work around only exists on the iPad and not on desktop Safari).

For reference, here's the desktop Safair's user agent: 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15

Maybe `navigator.platform` would help? On MacOS it's `MacIntel`. What is it on iPad iOS 13?

**Comment by deminoth** [comment] 2019-12-17 08:20
It's `MacIntel` on default desktop mode :(
If user select "Requst Mobile Site" manually, `navigator.userAgent` is `Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1` and `navigator.platform` is `iPad`.

**Comment by iangilman** [comment] 2019-12-17 17:47
Hmm. Looks like it's really hard! There are some thoughts here:

https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up

...but they are all pretty hacky. That said, it's worth figuring something out, to avoid the crash! Also, if we get a false positive (thinking some desktop Safari is an iPad Safari), all we're losing is the `smoothTileEdgesMinZoom` on those devices, so it's not the end of the world.

Of the suggestions list at the above link, checking `navigator.maxTouchPoints` (along with other things like `Safari` and maybe `MacIntel`) seems reasonable. What do you think?

**Comment by deminoth** [comment] 2019-12-18 07:30
It looks good. But we need to make sure that #952 is not fixed on recent iOS. I can't reproduce it in my iPad Pro(with 13.3). If it was fixed, we don't need to detect the platform.

**Comment by iangilman** [comment] 2019-12-18 21:31
Good point! I guess the theory above is that the crash reported by @sanli on iPadOS 13.1.3 might be #952. You're suggesting maybe it's been fixed by 13.3?

@sanli Can you confirm one way or the other? If you upgrade your iPad to 13.3, can you still get the crash? If so, does adding `iOSDevice: true` to your options fix it?

**Comment by msalsbery** [comment] 2020-08-09 00:05
Fixed for 2.4.3

**Comment by msalsbery** [comment] 2020-08-13 17:53
@sanli 

I'm finishing up an event-handling (MouseTracker) patch and I'm curious if the new code improves the issues you're seeing.

If you have a little time to try it out, I would love to hear your feedback!

[Links to Demos and Preview Builds](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)

Cheers

**Comment by msalsbery** [comment] 2021-03-09 19:07
Fixed for v2.5.0 (#1872)

Feel free to reopen if issue persists!

**Closed by msalsbery** 2021-03-09 19:07 UTC
Labels: duplicate
